// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=164,HLS_SYN_LUT=779,HLS_VERSION=2023_1}" *)

module matrixcalc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_0,
        a_0_1,
        a_0_2,
        a_1_0,
        a_1_1,
        a_1_2,
        a_2_0,
        a_2_1,
        a_2_2,
        b_0_0,
        b_0_1,
        b_0_2,
        b_1_0,
        b_1_1,
        b_1_2,
        b_2_0,
        b_2_1,
        b_2_2,
        c_0_0,
        c_0_1,
        c_0_2,
        c_1_0,
        c_1_1,
        c_1_2,
        c_2_0,
        c_2_1,
        c_2_2,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] a_0_0;
input  [3:0] a_0_1;
input  [3:0] a_0_2;
input  [3:0] a_1_0;
input  [3:0] a_1_1;
input  [3:0] a_1_2;
input  [3:0] a_2_0;
input  [3:0] a_2_1;
input  [3:0] a_2_2;
input  [3:0] b_0_0;
input  [3:0] b_0_1;
input  [3:0] b_0_2;
input  [3:0] b_1_0;
input  [3:0] b_1_1;
input  [3:0] b_1_2;
input  [3:0] b_2_0;
input  [3:0] b_2_1;
input  [3:0] b_2_2;
input  [3:0] c_0_0;
input  [3:0] c_0_1;
input  [3:0] c_0_2;
input  [3:0] c_1_0;
input  [3:0] c_1_1;
input  [3:0] c_1_2;
input  [3:0] c_2_0;
input  [3:0] c_2_1;
input  [3:0] c_2_2;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [3:0] mul_ln43_fu_236_p2;
reg   [3:0] mul_ln43_reg_614;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] mul_ln43_3_fu_254_p2;
reg   [3:0] mul_ln43_3_reg_619;
wire   [3:0] mul_ln43_6_fu_272_p2;
reg   [3:0] mul_ln43_6_reg_624;
wire   [3:0] mul_ln43_9_fu_290_p2;
reg   [3:0] mul_ln43_9_reg_629;
wire   [3:0] mul_ln43_12_fu_308_p2;
reg   [3:0] mul_ln43_12_reg_634;
wire   [3:0] mul_ln43_15_fu_326_p2;
reg   [3:0] mul_ln43_15_reg_639;
wire   [3:0] mul_ln43_19_fu_350_p2;
reg   [3:0] mul_ln43_19_reg_644;
wire   [3:0] mul_ln43_22_fu_368_p2;
reg   [3:0] mul_ln43_22_reg_649;
wire   [3:0] mul_ln43_24_fu_380_p2;
reg   [3:0] mul_ln43_24_reg_654;
reg   [3:0] c_0_0_read_reg_659;
wire   [3:0] add_ln59_1_fu_398_p2;
reg   [3:0] add_ln59_1_reg_664;
reg   [3:0] c_0_1_read_reg_669;
wire   [3:0] add_ln59_7_fu_404_p2;
reg   [3:0] add_ln59_7_reg_674;
reg   [3:0] c_0_2_read_reg_679;
wire   [3:0] add_ln59_10_fu_410_p2;
reg   [3:0] add_ln59_10_reg_684;
reg   [3:0] c_1_0_read_reg_689;
wire   [3:0] add_ln59_13_fu_416_p2;
reg   [3:0] add_ln59_13_reg_694;
reg   [3:0] c_1_1_read_reg_699;
wire   [3:0] add_ln59_15_fu_422_p2;
reg   [3:0] add_ln59_15_reg_704;
reg   [3:0] c_1_2_read_reg_709;
wire   [3:0] add_ln59_17_fu_428_p2;
reg   [3:0] add_ln59_17_reg_714;
reg   [3:0] c_2_0_read_reg_719;
wire   [3:0] add_ln59_19_fu_434_p2;
reg   [3:0] add_ln59_19_reg_724;
reg   [3:0] c_2_1_read_reg_729;
wire   [3:0] add_ln59_22_fu_440_p2;
reg   [3:0] add_ln59_22_reg_734;
reg   [3:0] c_2_2_read_reg_739;
wire   [3:0] add_ln59_25_fu_446_p2;
reg   [3:0] add_ln59_25_reg_744;
wire  signed [3:0] add_ln59_3_fu_483_p2;
reg  signed [3:0] add_ln59_3_reg_749;
wire  signed [3:0] add_ln59_4_fu_492_p2;
reg  signed [3:0] add_ln59_4_reg_754;
wire  signed [3:0] product2_fu_510_p2;
reg  signed [3:0] product2_reg_759;
wire  signed [3:0] product2_2_fu_519_p2;
reg  signed [3:0] product2_2_reg_764;
wire  signed [3:0] mul_ln20_fu_533_p2;
reg  signed [3:0] mul_ln20_reg_769;
wire   [3:0] product2_6_fu_539_p2;
reg   [3:0] product2_6_reg_774;
wire   [3:0] product1_7_fu_545_p2;
reg   [3:0] product1_7_reg_779;
wire   [3:0] product2_7_fu_551_p2;
reg   [3:0] product2_7_reg_784;
wire   [3:0] product1_8_fu_557_p2;
reg   [3:0] product1_8_reg_789;
wire  signed [3:0] mul_ln21_2_fu_563_p2;
reg  signed [3:0] mul_ln21_2_reg_794;
wire   [3:0] product2_5_fu_573_p2;
reg   [3:0] product2_5_reg_799;
wire   [3:0] sumpos_3_fu_590_p2;
reg   [3:0] sumpos_3_reg_804;
wire   [3:0] add_ln24_fu_595_p2;
reg   [3:0] add_ln24_reg_809;
wire    ap_block_pp0_stage0;
wire   [3:0] mul_ln43_2_fu_248_p2;
wire   [3:0] mul_ln43_1_fu_242_p2;
wire   [3:0] mul_ln43_5_fu_266_p2;
wire   [3:0] mul_ln43_4_fu_260_p2;
wire   [3:0] mul_ln43_8_fu_284_p2;
wire   [3:0] mul_ln43_7_fu_278_p2;
wire   [3:0] mul_ln43_11_fu_302_p2;
wire   [3:0] mul_ln43_10_fu_296_p2;
wire   [3:0] mul_ln43_14_fu_320_p2;
wire   [3:0] mul_ln43_13_fu_314_p2;
wire   [3:0] mul_ln43_17_fu_338_p2;
wire   [3:0] mul_ln43_16_fu_332_p2;
wire   [3:0] mul_ln43_18_fu_344_p2;
wire   [3:0] mul_ln43_20_fu_356_p2;
wire   [3:0] mul_ln43_21_fu_362_p2;
wire   [3:0] mul_ln43_23_fu_374_p2;
wire   [3:0] mul_ln43_26_fu_392_p2;
wire   [3:0] mul_ln43_25_fu_386_p2;
wire   [3:0] add_ln59_fu_452_p2;
wire   [3:0] add_ln59_6_fu_461_p2;
wire   [3:0] add_ln59_9_fu_470_p2;
wire   [3:0] add_ln59_12_fu_479_p2;
wire   [3:0] add_ln59_14_fu_488_p2;
wire   [3:0] add_ln59_16_fu_497_p2;
wire   [3:0] add_ln59_18_fu_506_p2;
wire   [3:0] add_ln59_21_fu_515_p2;
wire   [3:0] add_ln59_24_fu_524_p2;
wire  signed [3:0] product1_fu_456_p2;
wire  signed [3:0] product2_4_fu_528_p2;
wire  signed [3:0] product2_6_fu_539_p0;
wire  signed [3:0] product1_4_fu_474_p2;
wire  signed [3:0] add_ln59_5_fu_501_p2;
wire  signed [3:0] product1_2_fu_465_p2;
wire  signed [3:0] product1_8_fu_557_p0;
wire  signed [3:0] sumpos_fu_581_p0;
wire  signed [3:0] sumpos_3_fu_590_p0;
wire   [3:0] sumpos_fu_581_p2;
wire   [3:0] product1_6_fu_569_p2;
wire   [3:0] sumneg_fu_601_p2;
wire   [3:0] sum_fu_605_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U1(
    .din0(b_0_0),
    .din1(a_0_0),
    .dout(mul_ln43_fu_236_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U2(
    .din0(b_1_0),
    .din1(a_0_1),
    .dout(mul_ln43_1_fu_242_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U3(
    .din0(b_2_0),
    .din1(a_0_2),
    .dout(mul_ln43_2_fu_248_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U4(
    .din0(b_0_1),
    .din1(a_0_0),
    .dout(mul_ln43_3_fu_254_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U5(
    .din0(b_1_1),
    .din1(a_0_1),
    .dout(mul_ln43_4_fu_260_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U6(
    .din0(b_2_1),
    .din1(a_0_2),
    .dout(mul_ln43_5_fu_266_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U7(
    .din0(b_0_2),
    .din1(a_0_0),
    .dout(mul_ln43_6_fu_272_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U8(
    .din0(b_1_2),
    .din1(a_0_1),
    .dout(mul_ln43_7_fu_278_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U9(
    .din0(b_2_2),
    .din1(a_0_2),
    .dout(mul_ln43_8_fu_284_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U10(
    .din0(a_1_0),
    .din1(b_0_0),
    .dout(mul_ln43_9_fu_290_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U11(
    .din0(a_1_1),
    .din1(b_1_0),
    .dout(mul_ln43_10_fu_296_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U12(
    .din0(a_1_2),
    .din1(b_2_0),
    .dout(mul_ln43_11_fu_302_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U13(
    .din0(a_1_0),
    .din1(b_0_1),
    .dout(mul_ln43_12_fu_308_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U14(
    .din0(a_1_1),
    .din1(b_1_1),
    .dout(mul_ln43_13_fu_314_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U15(
    .din0(a_1_2),
    .din1(b_2_1),
    .dout(mul_ln43_14_fu_320_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U16(
    .din0(a_1_0),
    .din1(b_0_2),
    .dout(mul_ln43_15_fu_326_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U17(
    .din0(a_1_1),
    .din1(b_1_2),
    .dout(mul_ln43_16_fu_332_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U18(
    .din0(a_1_2),
    .din1(b_2_2),
    .dout(mul_ln43_17_fu_338_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U19(
    .din0(a_2_0),
    .din1(b_0_0),
    .dout(mul_ln43_18_fu_344_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U20(
    .din0(a_2_1),
    .din1(b_1_0),
    .dout(mul_ln43_19_fu_350_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U21(
    .din0(a_2_2),
    .din1(b_2_0),
    .dout(mul_ln43_20_fu_356_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U22(
    .din0(a_2_0),
    .din1(b_0_1),
    .dout(mul_ln43_21_fu_362_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U23(
    .din0(a_2_1),
    .din1(b_1_1),
    .dout(mul_ln43_22_fu_368_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U24(
    .din0(a_2_2),
    .din1(b_2_1),
    .dout(mul_ln43_23_fu_374_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U25(
    .din0(a_2_0),
    .din1(b_0_2),
    .dout(mul_ln43_24_fu_380_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U26(
    .din0(a_2_1),
    .din1(b_1_2),
    .dout(mul_ln43_25_fu_386_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U27(
    .din0(a_2_2),
    .din1(b_2_2),
    .dout(mul_ln43_26_fu_392_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U28(
    .din0(product1_fu_456_p2),
    .din1(product2_4_fu_528_p2),
    .dout(mul_ln20_fu_533_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U29(
    .din0(product2_6_fu_539_p0),
    .din1(product1_4_fu_474_p2),
    .dout(product2_6_fu_539_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U30(
    .din0(add_ln59_5_fu_501_p2),
    .din1(product1_2_fu_465_p2),
    .dout(product1_7_fu_545_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U31(
    .din0(add_ln59_5_fu_501_p2),
    .din1(product1_fu_456_p2),
    .dout(product2_7_fu_551_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U32(
    .din0(product1_8_fu_557_p0),
    .din1(product1_4_fu_474_p2),
    .dout(product1_8_fu_557_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U33(
    .din0(product1_2_fu_465_p2),
    .din1(product2_4_fu_528_p2),
    .dout(mul_ln21_2_fu_563_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U34(
    .din0(mul_ln20_reg_769),
    .din1(add_ln59_4_reg_754),
    .dout(product1_6_fu_569_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U35(
    .din0(mul_ln21_2_reg_794),
    .din1(add_ln59_3_reg_749),
    .dout(product2_5_fu_573_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U36(
    .din0(sumpos_fu_581_p0),
    .din1(product2_reg_759),
    .dout(sumpos_fu_581_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U37(
    .din0(sumpos_3_fu_590_p0),
    .din1(product2_2_reg_764),
    .dout(sumpos_3_fu_590_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln24_reg_809 <= add_ln24_fu_595_p2;
        product2_5_reg_799 <= product2_5_fu_573_p2;
        sumpos_3_reg_804 <= sumpos_3_fu_590_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_10_reg_684 <= add_ln59_10_fu_410_p2;
        add_ln59_13_reg_694 <= add_ln59_13_fu_416_p2;
        add_ln59_15_reg_704 <= add_ln59_15_fu_422_p2;
        add_ln59_17_reg_714 <= add_ln59_17_fu_428_p2;
        add_ln59_19_reg_724 <= add_ln59_19_fu_434_p2;
        add_ln59_1_reg_664 <= add_ln59_1_fu_398_p2;
        add_ln59_22_reg_734 <= add_ln59_22_fu_440_p2;
        add_ln59_25_reg_744 <= add_ln59_25_fu_446_p2;
        add_ln59_3_reg_749 <= add_ln59_3_fu_483_p2;
        add_ln59_4_reg_754 <= add_ln59_4_fu_492_p2;
        add_ln59_7_reg_674 <= add_ln59_7_fu_404_p2;
        c_0_0_read_reg_659 <= c_0_0;
        c_0_1_read_reg_669 <= c_0_1;
        c_0_2_read_reg_679 <= c_0_2;
        c_1_0_read_reg_689 <= c_1_0;
        c_1_1_read_reg_699 <= c_1_1;
        c_1_2_read_reg_709 <= c_1_2;
        c_2_0_read_reg_719 <= c_2_0;
        c_2_1_read_reg_729 <= c_2_1;
        c_2_2_read_reg_739 <= c_2_2;
        mul_ln20_reg_769 <= mul_ln20_fu_533_p2;
        mul_ln21_2_reg_794 <= mul_ln21_2_fu_563_p2;
        mul_ln43_12_reg_634 <= mul_ln43_12_fu_308_p2;
        mul_ln43_15_reg_639 <= mul_ln43_15_fu_326_p2;
        mul_ln43_19_reg_644 <= mul_ln43_19_fu_350_p2;
        mul_ln43_22_reg_649 <= mul_ln43_22_fu_368_p2;
        mul_ln43_24_reg_654 <= mul_ln43_24_fu_380_p2;
        mul_ln43_3_reg_619 <= mul_ln43_3_fu_254_p2;
        mul_ln43_6_reg_624 <= mul_ln43_6_fu_272_p2;
        mul_ln43_9_reg_629 <= mul_ln43_9_fu_290_p2;
        mul_ln43_reg_614 <= mul_ln43_fu_236_p2;
        product1_7_reg_779 <= product1_7_fu_545_p2;
        product1_8_reg_789 <= product1_8_fu_557_p2;
        product2_2_reg_764 <= product2_2_fu_519_p2;
        product2_6_reg_774 <= product2_6_fu_539_p2;
        product2_7_reg_784 <= product2_7_fu_551_p2;
        product2_reg_759 <= product2_fu_510_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_595_p2 = (sumpos_fu_581_p2 + product1_6_fu_569_p2);

assign add_ln59_10_fu_410_p2 = (mul_ln43_8_fu_284_p2 + mul_ln43_7_fu_278_p2);

assign add_ln59_12_fu_479_p2 = (c_1_0_read_reg_689 + mul_ln43_9_reg_629);

assign add_ln59_13_fu_416_p2 = (mul_ln43_11_fu_302_p2 + mul_ln43_10_fu_296_p2);

assign add_ln59_14_fu_488_p2 = (c_1_1_read_reg_699 + mul_ln43_12_reg_634);

assign add_ln59_15_fu_422_p2 = (mul_ln43_14_fu_320_p2 + mul_ln43_13_fu_314_p2);

assign add_ln59_16_fu_497_p2 = (c_1_2_read_reg_709 + mul_ln43_15_reg_639);

assign add_ln59_17_fu_428_p2 = (mul_ln43_17_fu_338_p2 + mul_ln43_16_fu_332_p2);

assign add_ln59_18_fu_506_p2 = (c_2_0_read_reg_719 + mul_ln43_19_reg_644);

assign add_ln59_19_fu_434_p2 = (mul_ln43_18_fu_344_p2 + mul_ln43_20_fu_356_p2);

assign add_ln59_1_fu_398_p2 = (mul_ln43_2_fu_248_p2 + mul_ln43_1_fu_242_p2);

assign add_ln59_21_fu_515_p2 = (c_2_1_read_reg_729 + mul_ln43_22_reg_649);

assign add_ln59_22_fu_440_p2 = (mul_ln43_21_fu_362_p2 + mul_ln43_23_fu_374_p2);

assign add_ln59_24_fu_524_p2 = (c_2_2_read_reg_739 + mul_ln43_24_reg_654);

assign add_ln59_25_fu_446_p2 = (mul_ln43_26_fu_392_p2 + mul_ln43_25_fu_386_p2);

assign add_ln59_3_fu_483_p2 = (add_ln59_13_reg_694 + add_ln59_12_fu_479_p2);

assign add_ln59_4_fu_492_p2 = (add_ln59_15_reg_704 + add_ln59_14_fu_488_p2);

assign add_ln59_5_fu_501_p2 = (add_ln59_17_reg_714 + add_ln59_16_fu_497_p2);

assign add_ln59_6_fu_461_p2 = (c_0_1_read_reg_669 + mul_ln43_3_reg_619);

assign add_ln59_7_fu_404_p2 = (mul_ln43_5_fu_266_p2 + mul_ln43_4_fu_260_p2);

assign add_ln59_9_fu_470_p2 = (c_0_2_read_reg_679 + mul_ln43_6_reg_624);

assign add_ln59_fu_452_p2 = (c_0_0_read_reg_659 + mul_ln43_reg_614);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = $signed(sum_fu_605_p2);

assign product1_2_fu_465_p2 = (add_ln59_7_reg_674 + add_ln59_6_fu_461_p2);

assign product1_4_fu_474_p2 = (add_ln59_10_reg_684 + add_ln59_9_fu_470_p2);

assign product1_8_fu_557_p0 = (add_ln59_13_reg_694 + add_ln59_12_fu_479_p2);

assign product1_fu_456_p2 = (add_ln59_1_reg_664 + add_ln59_fu_452_p2);

assign product2_2_fu_519_p2 = (add_ln59_22_reg_734 + add_ln59_21_fu_515_p2);

assign product2_4_fu_528_p2 = (add_ln59_25_reg_744 + add_ln59_24_fu_524_p2);

assign product2_6_fu_539_p0 = (add_ln59_15_reg_704 + add_ln59_14_fu_488_p2);

assign product2_fu_510_p2 = (add_ln59_19_reg_724 + add_ln59_18_fu_506_p2);

assign sum_fu_605_p2 = (sumneg_fu_601_p2 - product2_5_reg_799);

assign sumneg_fu_601_p2 = (add_ln24_reg_809 + sumpos_3_reg_804);

assign sumpos_3_fu_590_p0 = (product1_8_reg_789 - product2_7_reg_784);

assign sumpos_fu_581_p0 = (product1_7_reg_779 - product2_6_reg_774);

endmodule //matrixcalc
