// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=164,HLS_SYN_LUT=779,HLS_VERSION=2023_1}" *)

module matrixcalc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_0,
        a_0_1,
        a_0_2,
        a_1_0,
        a_1_1,
        a_1_2,
        a_2_0,
        a_2_1,
        a_2_2,
        b_0_0,
        b_0_1,
        b_0_2,
        b_1_0,
        b_1_1,
        b_1_2,
        b_2_0,
        b_2_1,
        b_2_2,
        c_0_0,
        c_0_1,
        c_0_2,
        c_1_0,
        c_1_1,
        c_1_2,
        c_2_0,
        c_2_1,
        c_2_2,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] a_0_0;
input  [3:0] a_0_1;
input  [3:0] a_0_2;
input  [3:0] a_1_0;
input  [3:0] a_1_1;
input  [3:0] a_1_2;
input  [3:0] a_2_0;
input  [3:0] a_2_1;
input  [3:0] a_2_2;
input  [3:0] b_0_0;
input  [3:0] b_0_1;
input  [3:0] b_0_2;
input  [3:0] b_1_0;
input  [3:0] b_1_1;
input  [3:0] b_1_2;
input  [3:0] b_2_0;
input  [3:0] b_2_1;
input  [3:0] b_2_2;
input  [3:0] c_0_0;
input  [3:0] c_0_1;
input  [3:0] c_0_2;
input  [3:0] c_1_0;
input  [3:0] c_1_1;
input  [3:0] c_1_2;
input  [3:0] c_2_0;
input  [3:0] c_2_1;
input  [3:0] c_2_2;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [3:0] mul_ln43_fu_238_p2;
reg   [3:0] mul_ln43_reg_616;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] mul_ln43_3_fu_256_p2;
reg   [3:0] mul_ln43_3_reg_621;
wire   [3:0] mul_ln43_6_fu_274_p2;
reg   [3:0] mul_ln43_6_reg_626;
wire   [3:0] mul_ln43_9_fu_292_p2;
reg   [3:0] mul_ln43_9_reg_631;
wire   [3:0] mul_ln43_12_fu_310_p2;
reg   [3:0] mul_ln43_12_reg_636;
wire   [3:0] mul_ln43_15_fu_328_p2;
reg   [3:0] mul_ln43_15_reg_641;
wire   [3:0] mul_ln43_19_fu_352_p2;
reg   [3:0] mul_ln43_19_reg_646;
wire   [3:0] mul_ln43_22_fu_370_p2;
reg   [3:0] mul_ln43_22_reg_651;
wire   [3:0] mul_ln43_24_fu_382_p2;
reg   [3:0] mul_ln43_24_reg_656;
reg   [3:0] c_0_0_read_reg_661;
wire   [3:0] add_ln59_1_fu_400_p2;
reg   [3:0] add_ln59_1_reg_666;
reg   [3:0] c_0_1_read_reg_671;
wire   [3:0] add_ln59_7_fu_406_p2;
reg   [3:0] add_ln59_7_reg_676;
reg   [3:0] c_0_2_read_reg_681;
wire   [3:0] add_ln59_10_fu_412_p2;
reg   [3:0] add_ln59_10_reg_686;
reg   [3:0] c_1_0_read_reg_691;
wire   [3:0] add_ln59_13_fu_418_p2;
reg   [3:0] add_ln59_13_reg_696;
reg   [3:0] c_1_1_read_reg_701;
wire   [3:0] add_ln59_15_fu_424_p2;
reg   [3:0] add_ln59_15_reg_706;
reg   [3:0] c_1_2_read_reg_711;
wire   [3:0] add_ln59_17_fu_430_p2;
reg   [3:0] add_ln59_17_reg_716;
reg   [3:0] c_2_0_read_reg_721;
wire   [3:0] add_ln59_19_fu_436_p2;
reg   [3:0] add_ln59_19_reg_726;
reg   [3:0] c_2_1_read_reg_731;
wire   [3:0] add_ln59_22_fu_442_p2;
reg   [3:0] add_ln59_22_reg_736;
reg   [3:0] c_2_2_read_reg_741;
wire   [3:0] add_ln59_25_fu_448_p2;
reg   [3:0] add_ln59_25_reg_746;
wire  signed [3:0] add_ln59_3_fu_485_p2;
reg  signed [3:0] add_ln59_3_reg_751;
wire  signed [3:0] add_ln59_4_fu_494_p2;
reg  signed [3:0] add_ln59_4_reg_756;
wire  signed [3:0] product2_fu_512_p2;
reg  signed [3:0] product2_reg_761;
wire  signed [3:0] product2_2_fu_521_p2;
reg  signed [3:0] product2_2_reg_766;
wire  signed [3:0] mul_ln20_fu_535_p2;
reg  signed [3:0] mul_ln20_reg_771;
wire   [3:0] product2_6_fu_541_p2;
reg   [3:0] product2_6_reg_776;
wire   [3:0] product1_7_fu_547_p2;
reg   [3:0] product1_7_reg_781;
wire   [3:0] product2_7_fu_553_p2;
reg   [3:0] product2_7_reg_786;
wire   [3:0] product1_8_fu_559_p2;
reg   [3:0] product1_8_reg_791;
wire  signed [3:0] mul_ln21_2_fu_565_p2;
reg  signed [3:0] mul_ln21_2_reg_796;
wire   [3:0] product2_5_fu_575_p2;
reg   [3:0] product2_5_reg_801;
wire   [3:0] sumpos_3_fu_592_p2;
reg   [3:0] sumpos_3_reg_806;
wire   [3:0] add_ln24_fu_597_p2;
reg   [3:0] add_ln24_reg_811;
wire    ap_block_pp0_stage0;
wire   [3:0] mul_ln43_2_fu_250_p2;
wire   [3:0] mul_ln43_1_fu_244_p2;
wire   [3:0] mul_ln43_5_fu_268_p2;
wire   [3:0] mul_ln43_4_fu_262_p2;
wire   [3:0] mul_ln43_8_fu_286_p2;
wire   [3:0] mul_ln43_7_fu_280_p2;
wire   [3:0] mul_ln43_11_fu_304_p2;
wire   [3:0] mul_ln43_10_fu_298_p2;
wire   [3:0] mul_ln43_14_fu_322_p2;
wire   [3:0] mul_ln43_13_fu_316_p2;
wire   [3:0] mul_ln43_17_fu_340_p2;
wire   [3:0] mul_ln43_16_fu_334_p2;
wire   [3:0] mul_ln43_18_fu_346_p2;
wire   [3:0] mul_ln43_20_fu_358_p2;
wire   [3:0] mul_ln43_21_fu_364_p2;
wire   [3:0] mul_ln43_23_fu_376_p2;
wire   [3:0] mul_ln43_26_fu_394_p2;
wire   [3:0] mul_ln43_25_fu_388_p2;
wire   [3:0] add_ln59_fu_454_p2;
wire   [3:0] add_ln59_6_fu_463_p2;
wire   [3:0] add_ln59_9_fu_472_p2;
wire   [3:0] add_ln59_12_fu_481_p2;
wire   [3:0] add_ln59_14_fu_490_p2;
wire   [3:0] add_ln59_16_fu_499_p2;
wire   [3:0] add_ln59_18_fu_508_p2;
wire   [3:0] add_ln59_21_fu_517_p2;
wire   [3:0] add_ln59_24_fu_526_p2;
wire  signed [3:0] product1_fu_458_p2;
wire  signed [3:0] product2_4_fu_530_p2;
wire  signed [3:0] product2_6_fu_541_p0;
wire  signed [3:0] product1_4_fu_476_p2;
wire  signed [3:0] add_ln59_5_fu_503_p2;
wire  signed [3:0] product1_2_fu_467_p2;
wire  signed [3:0] product1_8_fu_559_p0;
wire  signed [3:0] sumpos_fu_583_p0;
wire  signed [3:0] sumpos_3_fu_592_p0;
wire   [3:0] sumpos_fu_583_p2;
wire   [3:0] product1_6_fu_571_p2;
wire   [3:0] sumneg_fu_603_p2;
wire   [3:0] sum_fu_607_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U1(
    .din0(b_0_0),
    .din1(a_0_0),
    .dout(mul_ln43_fu_238_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U2(
    .din0(b_1_0),
    .din1(a_0_1),
    .dout(mul_ln43_1_fu_244_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U3(
    .din0(b_2_0),
    .din1(a_0_2),
    .dout(mul_ln43_2_fu_250_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U4(
    .din0(b_0_1),
    .din1(a_0_0),
    .dout(mul_ln43_3_fu_256_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U5(
    .din0(b_1_1),
    .din1(a_0_1),
    .dout(mul_ln43_4_fu_262_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U6(
    .din0(b_2_1),
    .din1(a_0_2),
    .dout(mul_ln43_5_fu_268_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U7(
    .din0(b_0_2),
    .din1(a_0_0),
    .dout(mul_ln43_6_fu_274_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U8(
    .din0(b_1_2),
    .din1(a_0_1),
    .dout(mul_ln43_7_fu_280_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U9(
    .din0(b_2_2),
    .din1(a_0_2),
    .dout(mul_ln43_8_fu_286_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U10(
    .din0(a_1_0),
    .din1(b_0_0),
    .dout(mul_ln43_9_fu_292_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U11(
    .din0(a_1_1),
    .din1(b_1_0),
    .dout(mul_ln43_10_fu_298_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U12(
    .din0(a_1_2),
    .din1(b_2_0),
    .dout(mul_ln43_11_fu_304_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U13(
    .din0(a_1_0),
    .din1(b_0_1),
    .dout(mul_ln43_12_fu_310_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U14(
    .din0(a_1_1),
    .din1(b_1_1),
    .dout(mul_ln43_13_fu_316_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U15(
    .din0(a_1_2),
    .din1(b_2_1),
    .dout(mul_ln43_14_fu_322_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U16(
    .din0(a_1_0),
    .din1(b_0_2),
    .dout(mul_ln43_15_fu_328_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U17(
    .din0(a_1_1),
    .din1(b_1_2),
    .dout(mul_ln43_16_fu_334_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U18(
    .din0(a_1_2),
    .din1(b_2_2),
    .dout(mul_ln43_17_fu_340_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U19(
    .din0(a_2_0),
    .din1(b_0_0),
    .dout(mul_ln43_18_fu_346_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U20(
    .din0(a_2_1),
    .din1(b_1_0),
    .dout(mul_ln43_19_fu_352_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U21(
    .din0(a_2_2),
    .din1(b_2_0),
    .dout(mul_ln43_20_fu_358_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U22(
    .din0(a_2_0),
    .din1(b_0_1),
    .dout(mul_ln43_21_fu_364_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U23(
    .din0(a_2_1),
    .din1(b_1_1),
    .dout(mul_ln43_22_fu_370_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U24(
    .din0(a_2_2),
    .din1(b_2_1),
    .dout(mul_ln43_23_fu_376_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U25(
    .din0(a_2_0),
    .din1(b_0_2),
    .dout(mul_ln43_24_fu_382_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U26(
    .din0(a_2_1),
    .din1(b_1_2),
    .dout(mul_ln43_25_fu_388_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U27(
    .din0(a_2_2),
    .din1(b_2_2),
    .dout(mul_ln43_26_fu_394_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U28(
    .din0(product1_fu_458_p2),
    .din1(product2_4_fu_530_p2),
    .dout(mul_ln20_fu_535_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U29(
    .din0(product2_6_fu_541_p0),
    .din1(product1_4_fu_476_p2),
    .dout(product2_6_fu_541_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U30(
    .din0(add_ln59_5_fu_503_p2),
    .din1(product1_2_fu_467_p2),
    .dout(product1_7_fu_547_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U31(
    .din0(add_ln59_5_fu_503_p2),
    .din1(product1_fu_458_p2),
    .dout(product2_7_fu_553_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U32(
    .din0(product1_8_fu_559_p0),
    .din1(product1_4_fu_476_p2),
    .dout(product1_8_fu_559_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U33(
    .din0(product1_2_fu_467_p2),
    .din1(product2_4_fu_530_p2),
    .dout(mul_ln21_2_fu_565_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U34(
    .din0(mul_ln20_reg_771),
    .din1(add_ln59_4_reg_756),
    .dout(product1_6_fu_571_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U35(
    .din0(mul_ln21_2_reg_796),
    .din1(add_ln59_3_reg_751),
    .dout(product2_5_fu_575_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U36(
    .din0(sumpos_fu_583_p0),
    .din1(product2_reg_761),
    .dout(sumpos_fu_583_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U37(
    .din0(sumpos_3_fu_592_p0),
    .din1(product2_2_reg_766),
    .dout(sumpos_3_fu_592_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln24_reg_811 <= add_ln24_fu_597_p2;
        product2_5_reg_801 <= product2_5_fu_575_p2;
        sumpos_3_reg_806 <= sumpos_3_fu_592_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_10_reg_686 <= add_ln59_10_fu_412_p2;
        add_ln59_13_reg_696 <= add_ln59_13_fu_418_p2;
        add_ln59_15_reg_706 <= add_ln59_15_fu_424_p2;
        add_ln59_17_reg_716 <= add_ln59_17_fu_430_p2;
        add_ln59_19_reg_726 <= add_ln59_19_fu_436_p2;
        add_ln59_1_reg_666 <= add_ln59_1_fu_400_p2;
        add_ln59_22_reg_736 <= add_ln59_22_fu_442_p2;
        add_ln59_25_reg_746 <= add_ln59_25_fu_448_p2;
        add_ln59_3_reg_751 <= add_ln59_3_fu_485_p2;
        add_ln59_4_reg_756 <= add_ln59_4_fu_494_p2;
        add_ln59_7_reg_676 <= add_ln59_7_fu_406_p2;
        c_0_0_read_reg_661 <= c_0_0;
        c_0_1_read_reg_671 <= c_0_1;
        c_0_2_read_reg_681 <= c_0_2;
        c_1_0_read_reg_691 <= c_1_0;
        c_1_1_read_reg_701 <= c_1_1;
        c_1_2_read_reg_711 <= c_1_2;
        c_2_0_read_reg_721 <= c_2_0;
        c_2_1_read_reg_731 <= c_2_1;
        c_2_2_read_reg_741 <= c_2_2;
        mul_ln20_reg_771 <= mul_ln20_fu_535_p2;
        mul_ln21_2_reg_796 <= mul_ln21_2_fu_565_p2;
        mul_ln43_12_reg_636 <= mul_ln43_12_fu_310_p2;
        mul_ln43_15_reg_641 <= mul_ln43_15_fu_328_p2;
        mul_ln43_19_reg_646 <= mul_ln43_19_fu_352_p2;
        mul_ln43_22_reg_651 <= mul_ln43_22_fu_370_p2;
        mul_ln43_24_reg_656 <= mul_ln43_24_fu_382_p2;
        mul_ln43_3_reg_621 <= mul_ln43_3_fu_256_p2;
        mul_ln43_6_reg_626 <= mul_ln43_6_fu_274_p2;
        mul_ln43_9_reg_631 <= mul_ln43_9_fu_292_p2;
        mul_ln43_reg_616 <= mul_ln43_fu_238_p2;
        product1_7_reg_781 <= product1_7_fu_547_p2;
        product1_8_reg_791 <= product1_8_fu_559_p2;
        product2_2_reg_766 <= product2_2_fu_521_p2;
        product2_6_reg_776 <= product2_6_fu_541_p2;
        product2_7_reg_786 <= product2_7_fu_553_p2;
        product2_reg_761 <= product2_fu_512_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_597_p2 = (sumpos_fu_583_p2 + product1_6_fu_571_p2);

assign add_ln59_10_fu_412_p2 = (mul_ln43_8_fu_286_p2 + mul_ln43_7_fu_280_p2);

assign add_ln59_12_fu_481_p2 = (c_1_0_read_reg_691 + mul_ln43_9_reg_631);

assign add_ln59_13_fu_418_p2 = (mul_ln43_11_fu_304_p2 + mul_ln43_10_fu_298_p2);

assign add_ln59_14_fu_490_p2 = (c_1_1_read_reg_701 + mul_ln43_12_reg_636);

assign add_ln59_15_fu_424_p2 = (mul_ln43_14_fu_322_p2 + mul_ln43_13_fu_316_p2);

assign add_ln59_16_fu_499_p2 = (c_1_2_read_reg_711 + mul_ln43_15_reg_641);

assign add_ln59_17_fu_430_p2 = (mul_ln43_17_fu_340_p2 + mul_ln43_16_fu_334_p2);

assign add_ln59_18_fu_508_p2 = (c_2_0_read_reg_721 + mul_ln43_19_reg_646);

assign add_ln59_19_fu_436_p2 = (mul_ln43_18_fu_346_p2 + mul_ln43_20_fu_358_p2);

assign add_ln59_1_fu_400_p2 = (mul_ln43_2_fu_250_p2 + mul_ln43_1_fu_244_p2);

assign add_ln59_21_fu_517_p2 = (c_2_1_read_reg_731 + mul_ln43_22_reg_651);

assign add_ln59_22_fu_442_p2 = (mul_ln43_21_fu_364_p2 + mul_ln43_23_fu_376_p2);

assign add_ln59_24_fu_526_p2 = (c_2_2_read_reg_741 + mul_ln43_24_reg_656);

assign add_ln59_25_fu_448_p2 = (mul_ln43_26_fu_394_p2 + mul_ln43_25_fu_388_p2);

assign add_ln59_3_fu_485_p2 = (add_ln59_13_reg_696 + add_ln59_12_fu_481_p2);

assign add_ln59_4_fu_494_p2 = (add_ln59_15_reg_706 + add_ln59_14_fu_490_p2);

assign add_ln59_5_fu_503_p2 = (add_ln59_17_reg_716 + add_ln59_16_fu_499_p2);

assign add_ln59_6_fu_463_p2 = (c_0_1_read_reg_671 + mul_ln43_3_reg_621);

assign add_ln59_7_fu_406_p2 = (mul_ln43_5_fu_268_p2 + mul_ln43_4_fu_262_p2);

assign add_ln59_9_fu_472_p2 = (c_0_2_read_reg_681 + mul_ln43_6_reg_626);

assign add_ln59_fu_454_p2 = (c_0_0_read_reg_661 + mul_ln43_reg_616);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = $signed(sum_fu_607_p2);

assign product1_2_fu_467_p2 = (add_ln59_7_reg_676 + add_ln59_6_fu_463_p2);

assign product1_4_fu_476_p2 = (add_ln59_10_reg_686 + add_ln59_9_fu_472_p2);

assign product1_8_fu_559_p0 = (add_ln59_13_reg_696 + add_ln59_12_fu_481_p2);

assign product1_fu_458_p2 = (add_ln59_1_reg_666 + add_ln59_fu_454_p2);

assign product2_2_fu_521_p2 = (add_ln59_22_reg_736 + add_ln59_21_fu_517_p2);

assign product2_4_fu_530_p2 = (add_ln59_25_reg_746 + add_ln59_24_fu_526_p2);

assign product2_6_fu_541_p0 = (add_ln59_15_reg_706 + add_ln59_14_fu_490_p2);

assign product2_fu_512_p2 = (add_ln59_19_reg_726 + add_ln59_18_fu_508_p2);

assign sum_fu_607_p2 = (sumneg_fu_603_p2 - product2_5_reg_801);

assign sumneg_fu_603_p2 = (add_ln24_reg_811 + sumpos_3_reg_806);

assign sumpos_3_fu_592_p0 = (product1_8_reg_791 - product2_7_reg_786);

assign sumpos_fu_583_p0 = (product1_7_reg_781 - product2_6_reg_776);

endmodule //matrixcalc
