-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrixcalc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrixcalc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=164,HLS_SYN_LUT=779,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal mul_ln43_fu_240_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_reg_618 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal mul_ln43_3_fu_258_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_3_reg_623 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_6_fu_276_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_6_reg_628 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_9_fu_294_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_9_reg_633 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_12_fu_312_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_12_reg_638 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_15_fu_330_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_15_reg_643 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_19_fu_354_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_19_reg_648 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_22_fu_372_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_22_reg_653 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_24_fu_384_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_24_reg_658 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_0_read_reg_663 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_1_fu_402_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_1_reg_668 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_1_read_reg_673 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_7_fu_408_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_7_reg_678 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_2_read_reg_683 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_10_fu_414_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_10_reg_688 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_0_read_reg_693 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_13_fu_420_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_13_reg_698 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_1_read_reg_703 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_15_fu_426_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_15_reg_708 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_2_read_reg_713 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_17_fu_432_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_17_reg_718 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_0_read_reg_723 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_19_fu_438_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_19_reg_728 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_1_read_reg_733 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_22_fu_444_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_22_reg_738 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_2_read_reg_743 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_25_fu_450_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_25_reg_748 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_3_fu_487_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_3_reg_753 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_4_fu_496_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_4_reg_758 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_fu_514_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_reg_763 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_2_fu_523_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_2_reg_768 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln20_fu_537_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln20_reg_773 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_fu_543_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_reg_778 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_7_fu_549_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_7_reg_783 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_7_fu_555_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_7_reg_788 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_fu_561_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_reg_793 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln21_2_fu_567_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln21_2_reg_798 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_5_fu_577_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_5_reg_803 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_fu_594_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_reg_808 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln24_fu_599_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln24_reg_813 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln43_2_fu_252_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_1_fu_246_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_5_fu_270_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_4_fu_264_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_8_fu_288_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_7_fu_282_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_11_fu_306_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_10_fu_300_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_14_fu_324_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_13_fu_318_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_17_fu_342_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_16_fu_336_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_18_fu_348_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_20_fu_360_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_21_fu_366_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_23_fu_378_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_26_fu_396_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_25_fu_390_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_fu_456_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_6_fu_465_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_9_fu_474_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_12_fu_483_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_14_fu_492_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_16_fu_501_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_18_fu_510_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_21_fu_519_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_24_fu_528_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_fu_460_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_4_fu_532_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_fu_543_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_4_fu_478_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_5_fu_505_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_2_fu_469_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_fu_561_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_fu_585_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_fu_594_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_fu_585_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_6_fu_573_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumneg_fu_605_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_fu_609_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrixcalc_mul_4s_4s_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    mul_4s_4s_4_1_1_U1 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_0,
        din1 => a_0_0,
        dout => mul_ln43_fu_240_p2);

    mul_4s_4s_4_1_1_U2 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_0,
        din1 => a_0_1,
        dout => mul_ln43_1_fu_246_p2);

    mul_4s_4s_4_1_1_U3 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_0,
        din1 => a_0_2,
        dout => mul_ln43_2_fu_252_p2);

    mul_4s_4s_4_1_1_U4 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_1,
        din1 => a_0_0,
        dout => mul_ln43_3_fu_258_p2);

    mul_4s_4s_4_1_1_U5 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_1,
        din1 => a_0_1,
        dout => mul_ln43_4_fu_264_p2);

    mul_4s_4s_4_1_1_U6 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_1,
        din1 => a_0_2,
        dout => mul_ln43_5_fu_270_p2);

    mul_4s_4s_4_1_1_U7 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_2,
        din1 => a_0_0,
        dout => mul_ln43_6_fu_276_p2);

    mul_4s_4s_4_1_1_U8 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_2,
        din1 => a_0_1,
        dout => mul_ln43_7_fu_282_p2);

    mul_4s_4s_4_1_1_U9 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_2,
        din1 => a_0_2,
        dout => mul_ln43_8_fu_288_p2);

    mul_4s_4s_4_1_1_U10 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_0,
        dout => mul_ln43_9_fu_294_p2);

    mul_4s_4s_4_1_1_U11 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_0,
        dout => mul_ln43_10_fu_300_p2);

    mul_4s_4s_4_1_1_U12 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_0,
        dout => mul_ln43_11_fu_306_p2);

    mul_4s_4s_4_1_1_U13 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_1,
        dout => mul_ln43_12_fu_312_p2);

    mul_4s_4s_4_1_1_U14 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_1,
        dout => mul_ln43_13_fu_318_p2);

    mul_4s_4s_4_1_1_U15 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_1,
        dout => mul_ln43_14_fu_324_p2);

    mul_4s_4s_4_1_1_U16 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_2,
        dout => mul_ln43_15_fu_330_p2);

    mul_4s_4s_4_1_1_U17 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_2,
        dout => mul_ln43_16_fu_336_p2);

    mul_4s_4s_4_1_1_U18 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_2,
        dout => mul_ln43_17_fu_342_p2);

    mul_4s_4s_4_1_1_U19 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_0,
        dout => mul_ln43_18_fu_348_p2);

    mul_4s_4s_4_1_1_U20 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_0,
        dout => mul_ln43_19_fu_354_p2);

    mul_4s_4s_4_1_1_U21 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_0,
        dout => mul_ln43_20_fu_360_p2);

    mul_4s_4s_4_1_1_U22 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_1,
        dout => mul_ln43_21_fu_366_p2);

    mul_4s_4s_4_1_1_U23 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_1,
        dout => mul_ln43_22_fu_372_p2);

    mul_4s_4s_4_1_1_U24 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_1,
        dout => mul_ln43_23_fu_378_p2);

    mul_4s_4s_4_1_1_U25 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_2,
        dout => mul_ln43_24_fu_384_p2);

    mul_4s_4s_4_1_1_U26 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_2,
        dout => mul_ln43_25_fu_390_p2);

    mul_4s_4s_4_1_1_U27 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_2,
        dout => mul_ln43_26_fu_396_p2);

    mul_4s_4s_4_1_1_U28 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_fu_460_p2,
        din1 => product2_4_fu_532_p2,
        dout => mul_ln20_fu_537_p2);

    mul_4s_4s_4_1_1_U29 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product2_6_fu_543_p0,
        din1 => product1_4_fu_478_p2,
        dout => product2_6_fu_543_p2);

    mul_4s_4s_4_1_1_U30 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => add_ln59_5_fu_505_p2,
        din1 => product1_2_fu_469_p2,
        dout => product1_7_fu_549_p2);

    mul_4s_4s_4_1_1_U31 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => add_ln59_5_fu_505_p2,
        din1 => product1_fu_460_p2,
        dout => product2_7_fu_555_p2);

    mul_4s_4s_4_1_1_U32 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_8_fu_561_p0,
        din1 => product1_4_fu_478_p2,
        dout => product1_8_fu_561_p2);

    mul_4s_4s_4_1_1_U33 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_2_fu_469_p2,
        din1 => product2_4_fu_532_p2,
        dout => mul_ln21_2_fu_567_p2);

    mul_4s_4s_4_1_1_U34 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => mul_ln20_reg_773,
        din1 => add_ln59_4_reg_758,
        dout => product1_6_fu_573_p2);

    mul_4s_4s_4_1_1_U35 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => mul_ln21_2_reg_798,
        din1 => add_ln59_3_reg_753,
        dout => product2_5_fu_577_p2);

    mul_4s_4s_4_1_1_U36 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => sumpos_fu_585_p0,
        din1 => product2_reg_763,
        dout => sumpos_fu_585_p2);

    mul_4s_4s_4_1_1_U37 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => sumpos_3_fu_594_p0,
        din1 => product2_2_reg_768,
        dout => sumpos_3_fu_594_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln24_reg_813 <= add_ln24_fu_599_p2;
                product2_5_reg_803 <= product2_5_fu_577_p2;
                sumpos_3_reg_808 <= sumpos_3_fu_594_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln59_10_reg_688 <= add_ln59_10_fu_414_p2;
                add_ln59_13_reg_698 <= add_ln59_13_fu_420_p2;
                add_ln59_15_reg_708 <= add_ln59_15_fu_426_p2;
                add_ln59_17_reg_718 <= add_ln59_17_fu_432_p2;
                add_ln59_19_reg_728 <= add_ln59_19_fu_438_p2;
                add_ln59_1_reg_668 <= add_ln59_1_fu_402_p2;
                add_ln59_22_reg_738 <= add_ln59_22_fu_444_p2;
                add_ln59_25_reg_748 <= add_ln59_25_fu_450_p2;
                add_ln59_3_reg_753 <= add_ln59_3_fu_487_p2;
                add_ln59_4_reg_758 <= add_ln59_4_fu_496_p2;
                add_ln59_7_reg_678 <= add_ln59_7_fu_408_p2;
                c_0_0_read_reg_663 <= c_0_0;
                c_0_1_read_reg_673 <= c_0_1;
                c_0_2_read_reg_683 <= c_0_2;
                c_1_0_read_reg_693 <= c_1_0;
                c_1_1_read_reg_703 <= c_1_1;
                c_1_2_read_reg_713 <= c_1_2;
                c_2_0_read_reg_723 <= c_2_0;
                c_2_1_read_reg_733 <= c_2_1;
                c_2_2_read_reg_743 <= c_2_2;
                mul_ln20_reg_773 <= mul_ln20_fu_537_p2;
                mul_ln21_2_reg_798 <= mul_ln21_2_fu_567_p2;
                mul_ln43_12_reg_638 <= mul_ln43_12_fu_312_p2;
                mul_ln43_15_reg_643 <= mul_ln43_15_fu_330_p2;
                mul_ln43_19_reg_648 <= mul_ln43_19_fu_354_p2;
                mul_ln43_22_reg_653 <= mul_ln43_22_fu_372_p2;
                mul_ln43_24_reg_658 <= mul_ln43_24_fu_384_p2;
                mul_ln43_3_reg_623 <= mul_ln43_3_fu_258_p2;
                mul_ln43_6_reg_628 <= mul_ln43_6_fu_276_p2;
                mul_ln43_9_reg_633 <= mul_ln43_9_fu_294_p2;
                mul_ln43_reg_618 <= mul_ln43_fu_240_p2;
                product1_7_reg_783 <= product1_7_fu_549_p2;
                product1_8_reg_793 <= product1_8_fu_561_p2;
                product2_2_reg_768 <= product2_2_fu_523_p2;
                product2_6_reg_778 <= product2_6_fu_543_p2;
                product2_7_reg_788 <= product2_7_fu_555_p2;
                product2_reg_763 <= product2_fu_514_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln24_fu_599_p2 <= std_logic_vector(unsigned(sumpos_fu_585_p2) + unsigned(product1_6_fu_573_p2));
    add_ln59_10_fu_414_p2 <= std_logic_vector(unsigned(mul_ln43_8_fu_288_p2) + unsigned(mul_ln43_7_fu_282_p2));
    add_ln59_12_fu_483_p2 <= std_logic_vector(unsigned(c_1_0_read_reg_693) + unsigned(mul_ln43_9_reg_633));
    add_ln59_13_fu_420_p2 <= std_logic_vector(unsigned(mul_ln43_11_fu_306_p2) + unsigned(mul_ln43_10_fu_300_p2));
    add_ln59_14_fu_492_p2 <= std_logic_vector(unsigned(c_1_1_read_reg_703) + unsigned(mul_ln43_12_reg_638));
    add_ln59_15_fu_426_p2 <= std_logic_vector(unsigned(mul_ln43_14_fu_324_p2) + unsigned(mul_ln43_13_fu_318_p2));
    add_ln59_16_fu_501_p2 <= std_logic_vector(unsigned(c_1_2_read_reg_713) + unsigned(mul_ln43_15_reg_643));
    add_ln59_17_fu_432_p2 <= std_logic_vector(unsigned(mul_ln43_17_fu_342_p2) + unsigned(mul_ln43_16_fu_336_p2));
    add_ln59_18_fu_510_p2 <= std_logic_vector(unsigned(c_2_0_read_reg_723) + unsigned(mul_ln43_19_reg_648));
    add_ln59_19_fu_438_p2 <= std_logic_vector(unsigned(mul_ln43_18_fu_348_p2) + unsigned(mul_ln43_20_fu_360_p2));
    add_ln59_1_fu_402_p2 <= std_logic_vector(unsigned(mul_ln43_2_fu_252_p2) + unsigned(mul_ln43_1_fu_246_p2));
    add_ln59_21_fu_519_p2 <= std_logic_vector(unsigned(c_2_1_read_reg_733) + unsigned(mul_ln43_22_reg_653));
    add_ln59_22_fu_444_p2 <= std_logic_vector(unsigned(mul_ln43_21_fu_366_p2) + unsigned(mul_ln43_23_fu_378_p2));
    add_ln59_24_fu_528_p2 <= std_logic_vector(unsigned(c_2_2_read_reg_743) + unsigned(mul_ln43_24_reg_658));
    add_ln59_25_fu_450_p2 <= std_logic_vector(unsigned(mul_ln43_26_fu_396_p2) + unsigned(mul_ln43_25_fu_390_p2));
    add_ln59_3_fu_487_p2 <= std_logic_vector(unsigned(add_ln59_13_reg_698) + unsigned(add_ln59_12_fu_483_p2));
    add_ln59_4_fu_496_p2 <= std_logic_vector(unsigned(add_ln59_15_reg_708) + unsigned(add_ln59_14_fu_492_p2));
    add_ln59_5_fu_505_p2 <= std_logic_vector(unsigned(add_ln59_17_reg_718) + unsigned(add_ln59_16_fu_501_p2));
    add_ln59_6_fu_465_p2 <= std_logic_vector(unsigned(c_0_1_read_reg_673) + unsigned(mul_ln43_3_reg_623));
    add_ln59_7_fu_408_p2 <= std_logic_vector(unsigned(mul_ln43_5_fu_270_p2) + unsigned(mul_ln43_4_fu_264_p2));
    add_ln59_9_fu_474_p2 <= std_logic_vector(unsigned(c_0_2_read_reg_683) + unsigned(mul_ln43_6_reg_628));
    add_ln59_fu_456_p2 <= std_logic_vector(unsigned(c_0_0_read_reg_663) + unsigned(mul_ln43_reg_618));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to2)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

        ap_return <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_fu_609_p2),32));

    product1_2_fu_469_p2 <= std_logic_vector(unsigned(add_ln59_7_reg_678) + unsigned(add_ln59_6_fu_465_p2));
    product1_4_fu_478_p2 <= std_logic_vector(unsigned(add_ln59_10_reg_688) + unsigned(add_ln59_9_fu_474_p2));
    product1_8_fu_561_p0 <= std_logic_vector(unsigned(add_ln59_13_reg_698) + unsigned(add_ln59_12_fu_483_p2));
    product1_fu_460_p2 <= std_logic_vector(unsigned(add_ln59_1_reg_668) + unsigned(add_ln59_fu_456_p2));
    product2_2_fu_523_p2 <= std_logic_vector(unsigned(add_ln59_22_reg_738) + unsigned(add_ln59_21_fu_519_p2));
    product2_4_fu_532_p2 <= std_logic_vector(unsigned(add_ln59_25_reg_748) + unsigned(add_ln59_24_fu_528_p2));
    product2_6_fu_543_p0 <= std_logic_vector(unsigned(add_ln59_15_reg_708) + unsigned(add_ln59_14_fu_492_p2));
    product2_fu_514_p2 <= std_logic_vector(unsigned(add_ln59_19_reg_728) + unsigned(add_ln59_18_fu_510_p2));
    sum_fu_609_p2 <= std_logic_vector(unsigned(sumneg_fu_605_p2) - unsigned(product2_5_reg_803));
    sumneg_fu_605_p2 <= std_logic_vector(unsigned(add_ln24_reg_813) + unsigned(sumpos_3_reg_808));
    sumpos_3_fu_594_p0 <= std_logic_vector(unsigned(product1_8_reg_793) - unsigned(product2_7_reg_788));
    sumpos_fu_585_p0 <= std_logic_vector(unsigned(product1_7_reg_783) - unsigned(product2_6_reg_778));
end behav;
