-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrixcalc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    a_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_0_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_1_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_2_2 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrixcalc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=164,HLS_SYN_LUT=779,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal mul_ln43_fu_238_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_reg_616 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal mul_ln43_3_fu_256_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_3_reg_621 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_6_fu_274_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_6_reg_626 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_9_fu_292_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_9_reg_631 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_12_fu_310_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_12_reg_636 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_15_fu_328_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_15_reg_641 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_19_fu_352_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_19_reg_646 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_22_fu_370_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_22_reg_651 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_24_fu_382_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_24_reg_656 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_0_read_reg_661 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_1_fu_400_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_1_reg_666 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_1_read_reg_671 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_7_fu_406_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_7_reg_676 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_0_2_read_reg_681 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_10_fu_412_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_10_reg_686 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_0_read_reg_691 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_13_fu_418_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_13_reg_696 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_1_read_reg_701 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_15_fu_424_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_15_reg_706 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_1_2_read_reg_711 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_17_fu_430_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_17_reg_716 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_0_read_reg_721 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_19_fu_436_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_19_reg_726 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_1_read_reg_731 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_22_fu_442_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_22_reg_736 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_2_2_read_reg_741 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_25_fu_448_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_25_reg_746 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_3_fu_485_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_3_reg_751 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_4_fu_494_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_4_reg_756 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_fu_512_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_reg_761 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_2_fu_521_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_2_reg_766 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln20_fu_535_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln20_reg_771 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_fu_541_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_reg_776 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_7_fu_547_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_7_reg_781 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_7_fu_553_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_7_reg_786 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_fu_559_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_reg_791 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln21_2_fu_565_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln21_2_reg_796 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_5_fu_575_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_5_reg_801 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_fu_592_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_reg_806 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln24_fu_597_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln24_reg_811 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln43_2_fu_250_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_1_fu_244_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_5_fu_268_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_4_fu_262_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_8_fu_286_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_7_fu_280_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_11_fu_304_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_10_fu_298_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_14_fu_322_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_13_fu_316_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_17_fu_340_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_16_fu_334_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_18_fu_346_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_20_fu_358_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_21_fu_364_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_23_fu_376_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_26_fu_394_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln43_25_fu_388_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_fu_454_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_6_fu_463_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_9_fu_472_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_12_fu_481_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_14_fu_490_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_16_fu_499_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_18_fu_508_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_21_fu_517_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_24_fu_526_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_fu_458_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_4_fu_530_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product2_6_fu_541_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_4_fu_476_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln59_5_fu_503_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_2_fu_467_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_8_fu_559_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_fu_583_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_3_fu_592_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumpos_fu_583_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal product1_6_fu_571_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumneg_fu_603_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_fu_607_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrixcalc_mul_4s_4s_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    mul_4s_4s_4_1_1_U1 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_0,
        din1 => a_0_0,
        dout => mul_ln43_fu_238_p2);

    mul_4s_4s_4_1_1_U2 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_0,
        din1 => a_0_1,
        dout => mul_ln43_1_fu_244_p2);

    mul_4s_4s_4_1_1_U3 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_0,
        din1 => a_0_2,
        dout => mul_ln43_2_fu_250_p2);

    mul_4s_4s_4_1_1_U4 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_1,
        din1 => a_0_0,
        dout => mul_ln43_3_fu_256_p2);

    mul_4s_4s_4_1_1_U5 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_1,
        din1 => a_0_1,
        dout => mul_ln43_4_fu_262_p2);

    mul_4s_4s_4_1_1_U6 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_1,
        din1 => a_0_2,
        dout => mul_ln43_5_fu_268_p2);

    mul_4s_4s_4_1_1_U7 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_0_2,
        din1 => a_0_0,
        dout => mul_ln43_6_fu_274_p2);

    mul_4s_4s_4_1_1_U8 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_1_2,
        din1 => a_0_1,
        dout => mul_ln43_7_fu_280_p2);

    mul_4s_4s_4_1_1_U9 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => b_2_2,
        din1 => a_0_2,
        dout => mul_ln43_8_fu_286_p2);

    mul_4s_4s_4_1_1_U10 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_0,
        dout => mul_ln43_9_fu_292_p2);

    mul_4s_4s_4_1_1_U11 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_0,
        dout => mul_ln43_10_fu_298_p2);

    mul_4s_4s_4_1_1_U12 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_0,
        dout => mul_ln43_11_fu_304_p2);

    mul_4s_4s_4_1_1_U13 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_1,
        dout => mul_ln43_12_fu_310_p2);

    mul_4s_4s_4_1_1_U14 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_1,
        dout => mul_ln43_13_fu_316_p2);

    mul_4s_4s_4_1_1_U15 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_1,
        dout => mul_ln43_14_fu_322_p2);

    mul_4s_4s_4_1_1_U16 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_0,
        din1 => b_0_2,
        dout => mul_ln43_15_fu_328_p2);

    mul_4s_4s_4_1_1_U17 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_1,
        din1 => b_1_2,
        dout => mul_ln43_16_fu_334_p2);

    mul_4s_4s_4_1_1_U18 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_1_2,
        din1 => b_2_2,
        dout => mul_ln43_17_fu_340_p2);

    mul_4s_4s_4_1_1_U19 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_0,
        dout => mul_ln43_18_fu_346_p2);

    mul_4s_4s_4_1_1_U20 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_0,
        dout => mul_ln43_19_fu_352_p2);

    mul_4s_4s_4_1_1_U21 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_0,
        dout => mul_ln43_20_fu_358_p2);

    mul_4s_4s_4_1_1_U22 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_1,
        dout => mul_ln43_21_fu_364_p2);

    mul_4s_4s_4_1_1_U23 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_1,
        dout => mul_ln43_22_fu_370_p2);

    mul_4s_4s_4_1_1_U24 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_1,
        dout => mul_ln43_23_fu_376_p2);

    mul_4s_4s_4_1_1_U25 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_0,
        din1 => b_0_2,
        dout => mul_ln43_24_fu_382_p2);

    mul_4s_4s_4_1_1_U26 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_1,
        din1 => b_1_2,
        dout => mul_ln43_25_fu_388_p2);

    mul_4s_4s_4_1_1_U27 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => a_2_2,
        din1 => b_2_2,
        dout => mul_ln43_26_fu_394_p2);

    mul_4s_4s_4_1_1_U28 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_fu_458_p2,
        din1 => product2_4_fu_530_p2,
        dout => mul_ln20_fu_535_p2);

    mul_4s_4s_4_1_1_U29 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product2_6_fu_541_p0,
        din1 => product1_4_fu_476_p2,
        dout => product2_6_fu_541_p2);

    mul_4s_4s_4_1_1_U30 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => add_ln59_5_fu_503_p2,
        din1 => product1_2_fu_467_p2,
        dout => product1_7_fu_547_p2);

    mul_4s_4s_4_1_1_U31 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => add_ln59_5_fu_503_p2,
        din1 => product1_fu_458_p2,
        dout => product2_7_fu_553_p2);

    mul_4s_4s_4_1_1_U32 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_8_fu_559_p0,
        din1 => product1_4_fu_476_p2,
        dout => product1_8_fu_559_p2);

    mul_4s_4s_4_1_1_U33 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => product1_2_fu_467_p2,
        din1 => product2_4_fu_530_p2,
        dout => mul_ln21_2_fu_565_p2);

    mul_4s_4s_4_1_1_U34 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => mul_ln20_reg_771,
        din1 => add_ln59_4_reg_756,
        dout => product1_6_fu_571_p2);

    mul_4s_4s_4_1_1_U35 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => mul_ln21_2_reg_796,
        din1 => add_ln59_3_reg_751,
        dout => product2_5_fu_575_p2);

    mul_4s_4s_4_1_1_U36 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => sumpos_fu_583_p0,
        din1 => product2_reg_761,
        dout => sumpos_fu_583_p2);

    mul_4s_4s_4_1_1_U37 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => sumpos_3_fu_592_p0,
        din1 => product2_2_reg_766,
        dout => sumpos_3_fu_592_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln24_reg_811 <= add_ln24_fu_597_p2;
                product2_5_reg_801 <= product2_5_fu_575_p2;
                sumpos_3_reg_806 <= sumpos_3_fu_592_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln59_10_reg_686 <= add_ln59_10_fu_412_p2;
                add_ln59_13_reg_696 <= add_ln59_13_fu_418_p2;
                add_ln59_15_reg_706 <= add_ln59_15_fu_424_p2;
                add_ln59_17_reg_716 <= add_ln59_17_fu_430_p2;
                add_ln59_19_reg_726 <= add_ln59_19_fu_436_p2;
                add_ln59_1_reg_666 <= add_ln59_1_fu_400_p2;
                add_ln59_22_reg_736 <= add_ln59_22_fu_442_p2;
                add_ln59_25_reg_746 <= add_ln59_25_fu_448_p2;
                add_ln59_3_reg_751 <= add_ln59_3_fu_485_p2;
                add_ln59_4_reg_756 <= add_ln59_4_fu_494_p2;
                add_ln59_7_reg_676 <= add_ln59_7_fu_406_p2;
                c_0_0_read_reg_661 <= c_0_0;
                c_0_1_read_reg_671 <= c_0_1;
                c_0_2_read_reg_681 <= c_0_2;
                c_1_0_read_reg_691 <= c_1_0;
                c_1_1_read_reg_701 <= c_1_1;
                c_1_2_read_reg_711 <= c_1_2;
                c_2_0_read_reg_721 <= c_2_0;
                c_2_1_read_reg_731 <= c_2_1;
                c_2_2_read_reg_741 <= c_2_2;
                mul_ln20_reg_771 <= mul_ln20_fu_535_p2;
                mul_ln21_2_reg_796 <= mul_ln21_2_fu_565_p2;
                mul_ln43_12_reg_636 <= mul_ln43_12_fu_310_p2;
                mul_ln43_15_reg_641 <= mul_ln43_15_fu_328_p2;
                mul_ln43_19_reg_646 <= mul_ln43_19_fu_352_p2;
                mul_ln43_22_reg_651 <= mul_ln43_22_fu_370_p2;
                mul_ln43_24_reg_656 <= mul_ln43_24_fu_382_p2;
                mul_ln43_3_reg_621 <= mul_ln43_3_fu_256_p2;
                mul_ln43_6_reg_626 <= mul_ln43_6_fu_274_p2;
                mul_ln43_9_reg_631 <= mul_ln43_9_fu_292_p2;
                mul_ln43_reg_616 <= mul_ln43_fu_238_p2;
                product1_7_reg_781 <= product1_7_fu_547_p2;
                product1_8_reg_791 <= product1_8_fu_559_p2;
                product2_2_reg_766 <= product2_2_fu_521_p2;
                product2_6_reg_776 <= product2_6_fu_541_p2;
                product2_7_reg_786 <= product2_7_fu_553_p2;
                product2_reg_761 <= product2_fu_512_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln24_fu_597_p2 <= std_logic_vector(unsigned(sumpos_fu_583_p2) + unsigned(product1_6_fu_571_p2));
    add_ln59_10_fu_412_p2 <= std_logic_vector(unsigned(mul_ln43_8_fu_286_p2) + unsigned(mul_ln43_7_fu_280_p2));
    add_ln59_12_fu_481_p2 <= std_logic_vector(unsigned(c_1_0_read_reg_691) + unsigned(mul_ln43_9_reg_631));
    add_ln59_13_fu_418_p2 <= std_logic_vector(unsigned(mul_ln43_11_fu_304_p2) + unsigned(mul_ln43_10_fu_298_p2));
    add_ln59_14_fu_490_p2 <= std_logic_vector(unsigned(c_1_1_read_reg_701) + unsigned(mul_ln43_12_reg_636));
    add_ln59_15_fu_424_p2 <= std_logic_vector(unsigned(mul_ln43_14_fu_322_p2) + unsigned(mul_ln43_13_fu_316_p2));
    add_ln59_16_fu_499_p2 <= std_logic_vector(unsigned(c_1_2_read_reg_711) + unsigned(mul_ln43_15_reg_641));
    add_ln59_17_fu_430_p2 <= std_logic_vector(unsigned(mul_ln43_17_fu_340_p2) + unsigned(mul_ln43_16_fu_334_p2));
    add_ln59_18_fu_508_p2 <= std_logic_vector(unsigned(c_2_0_read_reg_721) + unsigned(mul_ln43_19_reg_646));
    add_ln59_19_fu_436_p2 <= std_logic_vector(unsigned(mul_ln43_18_fu_346_p2) + unsigned(mul_ln43_20_fu_358_p2));
    add_ln59_1_fu_400_p2 <= std_logic_vector(unsigned(mul_ln43_2_fu_250_p2) + unsigned(mul_ln43_1_fu_244_p2));
    add_ln59_21_fu_517_p2 <= std_logic_vector(unsigned(c_2_1_read_reg_731) + unsigned(mul_ln43_22_reg_651));
    add_ln59_22_fu_442_p2 <= std_logic_vector(unsigned(mul_ln43_21_fu_364_p2) + unsigned(mul_ln43_23_fu_376_p2));
    add_ln59_24_fu_526_p2 <= std_logic_vector(unsigned(c_2_2_read_reg_741) + unsigned(mul_ln43_24_reg_656));
    add_ln59_25_fu_448_p2 <= std_logic_vector(unsigned(mul_ln43_26_fu_394_p2) + unsigned(mul_ln43_25_fu_388_p2));
    add_ln59_3_fu_485_p2 <= std_logic_vector(unsigned(add_ln59_13_reg_696) + unsigned(add_ln59_12_fu_481_p2));
    add_ln59_4_fu_494_p2 <= std_logic_vector(unsigned(add_ln59_15_reg_706) + unsigned(add_ln59_14_fu_490_p2));
    add_ln59_5_fu_503_p2 <= std_logic_vector(unsigned(add_ln59_17_reg_716) + unsigned(add_ln59_16_fu_499_p2));
    add_ln59_6_fu_463_p2 <= std_logic_vector(unsigned(c_0_1_read_reg_671) + unsigned(mul_ln43_3_reg_621));
    add_ln59_7_fu_406_p2 <= std_logic_vector(unsigned(mul_ln43_5_fu_268_p2) + unsigned(mul_ln43_4_fu_262_p2));
    add_ln59_9_fu_472_p2 <= std_logic_vector(unsigned(c_0_2_read_reg_681) + unsigned(mul_ln43_6_reg_626));
    add_ln59_fu_454_p2 <= std_logic_vector(unsigned(c_0_0_read_reg_661) + unsigned(mul_ln43_reg_616));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to2)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

        ap_return <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_fu_607_p2),32));

    product1_2_fu_467_p2 <= std_logic_vector(unsigned(add_ln59_7_reg_676) + unsigned(add_ln59_6_fu_463_p2));
    product1_4_fu_476_p2 <= std_logic_vector(unsigned(add_ln59_10_reg_686) + unsigned(add_ln59_9_fu_472_p2));
    product1_8_fu_559_p0 <= std_logic_vector(unsigned(add_ln59_13_reg_696) + unsigned(add_ln59_12_fu_481_p2));
    product1_fu_458_p2 <= std_logic_vector(unsigned(add_ln59_1_reg_666) + unsigned(add_ln59_fu_454_p2));
    product2_2_fu_521_p2 <= std_logic_vector(unsigned(add_ln59_22_reg_736) + unsigned(add_ln59_21_fu_517_p2));
    product2_4_fu_530_p2 <= std_logic_vector(unsigned(add_ln59_25_reg_746) + unsigned(add_ln59_24_fu_526_p2));
    product2_6_fu_541_p0 <= std_logic_vector(unsigned(add_ln59_15_reg_706) + unsigned(add_ln59_14_fu_490_p2));
    product2_fu_512_p2 <= std_logic_vector(unsigned(add_ln59_19_reg_726) + unsigned(add_ln59_18_fu_508_p2));
    sum_fu_607_p2 <= std_logic_vector(unsigned(sumneg_fu_603_p2) - unsigned(product2_5_reg_801));
    sumneg_fu_603_p2 <= std_logic_vector(unsigned(add_ln24_reg_811) + unsigned(sumpos_3_reg_806));
    sumpos_3_fu_592_p0 <= std_logic_vector(unsigned(product1_8_reg_791) - unsigned(product2_7_reg_786));
    sumpos_fu_583_p0 <= std_logic_vector(unsigned(product1_7_reg_781) - unsigned(product2_6_reg_776));
end behav;
