// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.810000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=164,HLS_SYN_LUT=779,HLS_VERSION=2023_1}" *)

module matrixcalc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_0,
        a_0_1,
        a_0_2,
        a_1_0,
        a_1_1,
        a_1_2,
        a_2_0,
        a_2_1,
        a_2_2,
        b_0_0,
        b_0_1,
        b_0_2,
        b_1_0,
        b_1_1,
        b_1_2,
        b_2_0,
        b_2_1,
        b_2_2,
        c_0_0,
        c_0_1,
        c_0_2,
        c_1_0,
        c_1_1,
        c_1_2,
        c_2_0,
        c_2_1,
        c_2_2,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] a_0_0;
input  [3:0] a_0_1;
input  [3:0] a_0_2;
input  [3:0] a_1_0;
input  [3:0] a_1_1;
input  [3:0] a_1_2;
input  [3:0] a_2_0;
input  [3:0] a_2_1;
input  [3:0] a_2_2;
input  [3:0] b_0_0;
input  [3:0] b_0_1;
input  [3:0] b_0_2;
input  [3:0] b_1_0;
input  [3:0] b_1_1;
input  [3:0] b_1_2;
input  [3:0] b_2_0;
input  [3:0] b_2_1;
input  [3:0] b_2_2;
input  [3:0] c_0_0;
input  [3:0] c_0_1;
input  [3:0] c_0_2;
input  [3:0] c_1_0;
input  [3:0] c_1_1;
input  [3:0] c_1_2;
input  [3:0] c_2_0;
input  [3:0] c_2_1;
input  [3:0] c_2_2;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [3:0] mul_ln43_fu_240_p2;
reg   [3:0] mul_ln43_reg_618;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] mul_ln43_3_fu_258_p2;
reg   [3:0] mul_ln43_3_reg_623;
wire   [3:0] mul_ln43_6_fu_276_p2;
reg   [3:0] mul_ln43_6_reg_628;
wire   [3:0] mul_ln43_9_fu_294_p2;
reg   [3:0] mul_ln43_9_reg_633;
wire   [3:0] mul_ln43_12_fu_312_p2;
reg   [3:0] mul_ln43_12_reg_638;
wire   [3:0] mul_ln43_15_fu_330_p2;
reg   [3:0] mul_ln43_15_reg_643;
wire   [3:0] mul_ln43_19_fu_354_p2;
reg   [3:0] mul_ln43_19_reg_648;
wire   [3:0] mul_ln43_22_fu_372_p2;
reg   [3:0] mul_ln43_22_reg_653;
wire   [3:0] mul_ln43_24_fu_384_p2;
reg   [3:0] mul_ln43_24_reg_658;
reg   [3:0] c_0_0_read_reg_663;
wire   [3:0] add_ln59_1_fu_402_p2;
reg   [3:0] add_ln59_1_reg_668;
reg   [3:0] c_0_1_read_reg_673;
wire   [3:0] add_ln59_7_fu_408_p2;
reg   [3:0] add_ln59_7_reg_678;
reg   [3:0] c_0_2_read_reg_683;
wire   [3:0] add_ln59_10_fu_414_p2;
reg   [3:0] add_ln59_10_reg_688;
reg   [3:0] c_1_0_read_reg_693;
wire   [3:0] add_ln59_13_fu_420_p2;
reg   [3:0] add_ln59_13_reg_698;
reg   [3:0] c_1_1_read_reg_703;
wire   [3:0] add_ln59_15_fu_426_p2;
reg   [3:0] add_ln59_15_reg_708;
reg   [3:0] c_1_2_read_reg_713;
wire   [3:0] add_ln59_17_fu_432_p2;
reg   [3:0] add_ln59_17_reg_718;
reg   [3:0] c_2_0_read_reg_723;
wire   [3:0] add_ln59_19_fu_438_p2;
reg   [3:0] add_ln59_19_reg_728;
reg   [3:0] c_2_1_read_reg_733;
wire   [3:0] add_ln59_22_fu_444_p2;
reg   [3:0] add_ln59_22_reg_738;
reg   [3:0] c_2_2_read_reg_743;
wire   [3:0] add_ln59_25_fu_450_p2;
reg   [3:0] add_ln59_25_reg_748;
wire  signed [3:0] add_ln59_3_fu_487_p2;
reg  signed [3:0] add_ln59_3_reg_753;
wire  signed [3:0] add_ln59_4_fu_496_p2;
reg  signed [3:0] add_ln59_4_reg_758;
wire  signed [3:0] product2_fu_514_p2;
reg  signed [3:0] product2_reg_763;
wire  signed [3:0] product2_2_fu_523_p2;
reg  signed [3:0] product2_2_reg_768;
wire  signed [3:0] mul_ln20_fu_537_p2;
reg  signed [3:0] mul_ln20_reg_773;
wire   [3:0] product2_6_fu_543_p2;
reg   [3:0] product2_6_reg_778;
wire   [3:0] product1_7_fu_549_p2;
reg   [3:0] product1_7_reg_783;
wire   [3:0] product2_7_fu_555_p2;
reg   [3:0] product2_7_reg_788;
wire   [3:0] product1_8_fu_561_p2;
reg   [3:0] product1_8_reg_793;
wire  signed [3:0] mul_ln21_2_fu_567_p2;
reg  signed [3:0] mul_ln21_2_reg_798;
wire   [3:0] product2_5_fu_577_p2;
reg   [3:0] product2_5_reg_803;
wire   [3:0] sumpos_3_fu_594_p2;
reg   [3:0] sumpos_3_reg_808;
wire   [3:0] add_ln24_fu_599_p2;
reg   [3:0] add_ln24_reg_813;
wire    ap_block_pp0_stage0;
wire   [3:0] mul_ln43_2_fu_252_p2;
wire   [3:0] mul_ln43_1_fu_246_p2;
wire   [3:0] mul_ln43_5_fu_270_p2;
wire   [3:0] mul_ln43_4_fu_264_p2;
wire   [3:0] mul_ln43_8_fu_288_p2;
wire   [3:0] mul_ln43_7_fu_282_p2;
wire   [3:0] mul_ln43_11_fu_306_p2;
wire   [3:0] mul_ln43_10_fu_300_p2;
wire   [3:0] mul_ln43_14_fu_324_p2;
wire   [3:0] mul_ln43_13_fu_318_p2;
wire   [3:0] mul_ln43_17_fu_342_p2;
wire   [3:0] mul_ln43_16_fu_336_p2;
wire   [3:0] mul_ln43_18_fu_348_p2;
wire   [3:0] mul_ln43_20_fu_360_p2;
wire   [3:0] mul_ln43_21_fu_366_p2;
wire   [3:0] mul_ln43_23_fu_378_p2;
wire   [3:0] mul_ln43_26_fu_396_p2;
wire   [3:0] mul_ln43_25_fu_390_p2;
wire   [3:0] add_ln59_fu_456_p2;
wire   [3:0] add_ln59_6_fu_465_p2;
wire   [3:0] add_ln59_9_fu_474_p2;
wire   [3:0] add_ln59_12_fu_483_p2;
wire   [3:0] add_ln59_14_fu_492_p2;
wire   [3:0] add_ln59_16_fu_501_p2;
wire   [3:0] add_ln59_18_fu_510_p2;
wire   [3:0] add_ln59_21_fu_519_p2;
wire   [3:0] add_ln59_24_fu_528_p2;
wire  signed [3:0] product1_fu_460_p2;
wire  signed [3:0] product2_4_fu_532_p2;
wire  signed [3:0] product2_6_fu_543_p0;
wire  signed [3:0] product1_4_fu_478_p2;
wire  signed [3:0] add_ln59_5_fu_505_p2;
wire  signed [3:0] product1_2_fu_469_p2;
wire  signed [3:0] product1_8_fu_561_p0;
wire  signed [3:0] sumpos_fu_585_p0;
wire  signed [3:0] sumpos_3_fu_594_p0;
wire   [3:0] sumpos_fu_585_p2;
wire   [3:0] product1_6_fu_573_p2;
wire   [3:0] sumneg_fu_605_p2;
wire   [3:0] sum_fu_609_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U1(
    .din0(b_0_0),
    .din1(a_0_0),
    .dout(mul_ln43_fu_240_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U2(
    .din0(b_1_0),
    .din1(a_0_1),
    .dout(mul_ln43_1_fu_246_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U3(
    .din0(b_2_0),
    .din1(a_0_2),
    .dout(mul_ln43_2_fu_252_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U4(
    .din0(b_0_1),
    .din1(a_0_0),
    .dout(mul_ln43_3_fu_258_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U5(
    .din0(b_1_1),
    .din1(a_0_1),
    .dout(mul_ln43_4_fu_264_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U6(
    .din0(b_2_1),
    .din1(a_0_2),
    .dout(mul_ln43_5_fu_270_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U7(
    .din0(b_0_2),
    .din1(a_0_0),
    .dout(mul_ln43_6_fu_276_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U8(
    .din0(b_1_2),
    .din1(a_0_1),
    .dout(mul_ln43_7_fu_282_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U9(
    .din0(b_2_2),
    .din1(a_0_2),
    .dout(mul_ln43_8_fu_288_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U10(
    .din0(a_1_0),
    .din1(b_0_0),
    .dout(mul_ln43_9_fu_294_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U11(
    .din0(a_1_1),
    .din1(b_1_0),
    .dout(mul_ln43_10_fu_300_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U12(
    .din0(a_1_2),
    .din1(b_2_0),
    .dout(mul_ln43_11_fu_306_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U13(
    .din0(a_1_0),
    .din1(b_0_1),
    .dout(mul_ln43_12_fu_312_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U14(
    .din0(a_1_1),
    .din1(b_1_1),
    .dout(mul_ln43_13_fu_318_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U15(
    .din0(a_1_2),
    .din1(b_2_1),
    .dout(mul_ln43_14_fu_324_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U16(
    .din0(a_1_0),
    .din1(b_0_2),
    .dout(mul_ln43_15_fu_330_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U17(
    .din0(a_1_1),
    .din1(b_1_2),
    .dout(mul_ln43_16_fu_336_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U18(
    .din0(a_1_2),
    .din1(b_2_2),
    .dout(mul_ln43_17_fu_342_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U19(
    .din0(a_2_0),
    .din1(b_0_0),
    .dout(mul_ln43_18_fu_348_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U20(
    .din0(a_2_1),
    .din1(b_1_0),
    .dout(mul_ln43_19_fu_354_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U21(
    .din0(a_2_2),
    .din1(b_2_0),
    .dout(mul_ln43_20_fu_360_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U22(
    .din0(a_2_0),
    .din1(b_0_1),
    .dout(mul_ln43_21_fu_366_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U23(
    .din0(a_2_1),
    .din1(b_1_1),
    .dout(mul_ln43_22_fu_372_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U24(
    .din0(a_2_2),
    .din1(b_2_1),
    .dout(mul_ln43_23_fu_378_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U25(
    .din0(a_2_0),
    .din1(b_0_2),
    .dout(mul_ln43_24_fu_384_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U26(
    .din0(a_2_1),
    .din1(b_1_2),
    .dout(mul_ln43_25_fu_390_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U27(
    .din0(a_2_2),
    .din1(b_2_2),
    .dout(mul_ln43_26_fu_396_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U28(
    .din0(product1_fu_460_p2),
    .din1(product2_4_fu_532_p2),
    .dout(mul_ln20_fu_537_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U29(
    .din0(product2_6_fu_543_p0),
    .din1(product1_4_fu_478_p2),
    .dout(product2_6_fu_543_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U30(
    .din0(add_ln59_5_fu_505_p2),
    .din1(product1_2_fu_469_p2),
    .dout(product1_7_fu_549_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U31(
    .din0(add_ln59_5_fu_505_p2),
    .din1(product1_fu_460_p2),
    .dout(product2_7_fu_555_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U32(
    .din0(product1_8_fu_561_p0),
    .din1(product1_4_fu_478_p2),
    .dout(product1_8_fu_561_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U33(
    .din0(product1_2_fu_469_p2),
    .din1(product2_4_fu_532_p2),
    .dout(mul_ln21_2_fu_567_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U34(
    .din0(mul_ln20_reg_773),
    .din1(add_ln59_4_reg_758),
    .dout(product1_6_fu_573_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U35(
    .din0(mul_ln21_2_reg_798),
    .din1(add_ln59_3_reg_753),
    .dout(product2_5_fu_577_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U36(
    .din0(sumpos_fu_585_p0),
    .din1(product2_reg_763),
    .dout(sumpos_fu_585_p2)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U37(
    .din0(sumpos_3_fu_594_p0),
    .din1(product2_2_reg_768),
    .dout(sumpos_3_fu_594_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln24_reg_813 <= add_ln24_fu_599_p2;
        product2_5_reg_803 <= product2_5_fu_577_p2;
        sumpos_3_reg_808 <= sumpos_3_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln59_10_reg_688 <= add_ln59_10_fu_414_p2;
        add_ln59_13_reg_698 <= add_ln59_13_fu_420_p2;
        add_ln59_15_reg_708 <= add_ln59_15_fu_426_p2;
        add_ln59_17_reg_718 <= add_ln59_17_fu_432_p2;
        add_ln59_19_reg_728 <= add_ln59_19_fu_438_p2;
        add_ln59_1_reg_668 <= add_ln59_1_fu_402_p2;
        add_ln59_22_reg_738 <= add_ln59_22_fu_444_p2;
        add_ln59_25_reg_748 <= add_ln59_25_fu_450_p2;
        add_ln59_3_reg_753 <= add_ln59_3_fu_487_p2;
        add_ln59_4_reg_758 <= add_ln59_4_fu_496_p2;
        add_ln59_7_reg_678 <= add_ln59_7_fu_408_p2;
        c_0_0_read_reg_663 <= c_0_0;
        c_0_1_read_reg_673 <= c_0_1;
        c_0_2_read_reg_683 <= c_0_2;
        c_1_0_read_reg_693 <= c_1_0;
        c_1_1_read_reg_703 <= c_1_1;
        c_1_2_read_reg_713 <= c_1_2;
        c_2_0_read_reg_723 <= c_2_0;
        c_2_1_read_reg_733 <= c_2_1;
        c_2_2_read_reg_743 <= c_2_2;
        mul_ln20_reg_773 <= mul_ln20_fu_537_p2;
        mul_ln21_2_reg_798 <= mul_ln21_2_fu_567_p2;
        mul_ln43_12_reg_638 <= mul_ln43_12_fu_312_p2;
        mul_ln43_15_reg_643 <= mul_ln43_15_fu_330_p2;
        mul_ln43_19_reg_648 <= mul_ln43_19_fu_354_p2;
        mul_ln43_22_reg_653 <= mul_ln43_22_fu_372_p2;
        mul_ln43_24_reg_658 <= mul_ln43_24_fu_384_p2;
        mul_ln43_3_reg_623 <= mul_ln43_3_fu_258_p2;
        mul_ln43_6_reg_628 <= mul_ln43_6_fu_276_p2;
        mul_ln43_9_reg_633 <= mul_ln43_9_fu_294_p2;
        mul_ln43_reg_618 <= mul_ln43_fu_240_p2;
        product1_7_reg_783 <= product1_7_fu_549_p2;
        product1_8_reg_793 <= product1_8_fu_561_p2;
        product2_2_reg_768 <= product2_2_fu_523_p2;
        product2_6_reg_778 <= product2_6_fu_543_p2;
        product2_7_reg_788 <= product2_7_fu_555_p2;
        product2_reg_763 <= product2_fu_514_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln24_fu_599_p2 = (sumpos_fu_585_p2 + product1_6_fu_573_p2);

assign add_ln59_10_fu_414_p2 = (mul_ln43_8_fu_288_p2 + mul_ln43_7_fu_282_p2);

assign add_ln59_12_fu_483_p2 = (c_1_0_read_reg_693 + mul_ln43_9_reg_633);

assign add_ln59_13_fu_420_p2 = (mul_ln43_11_fu_306_p2 + mul_ln43_10_fu_300_p2);

assign add_ln59_14_fu_492_p2 = (c_1_1_read_reg_703 + mul_ln43_12_reg_638);

assign add_ln59_15_fu_426_p2 = (mul_ln43_14_fu_324_p2 + mul_ln43_13_fu_318_p2);

assign add_ln59_16_fu_501_p2 = (c_1_2_read_reg_713 + mul_ln43_15_reg_643);

assign add_ln59_17_fu_432_p2 = (mul_ln43_17_fu_342_p2 + mul_ln43_16_fu_336_p2);

assign add_ln59_18_fu_510_p2 = (c_2_0_read_reg_723 + mul_ln43_19_reg_648);

assign add_ln59_19_fu_438_p2 = (mul_ln43_18_fu_348_p2 + mul_ln43_20_fu_360_p2);

assign add_ln59_1_fu_402_p2 = (mul_ln43_2_fu_252_p2 + mul_ln43_1_fu_246_p2);

assign add_ln59_21_fu_519_p2 = (c_2_1_read_reg_733 + mul_ln43_22_reg_653);

assign add_ln59_22_fu_444_p2 = (mul_ln43_21_fu_366_p2 + mul_ln43_23_fu_378_p2);

assign add_ln59_24_fu_528_p2 = (c_2_2_read_reg_743 + mul_ln43_24_reg_658);

assign add_ln59_25_fu_450_p2 = (mul_ln43_26_fu_396_p2 + mul_ln43_25_fu_390_p2);

assign add_ln59_3_fu_487_p2 = (add_ln59_13_reg_698 + add_ln59_12_fu_483_p2);

assign add_ln59_4_fu_496_p2 = (add_ln59_15_reg_708 + add_ln59_14_fu_492_p2);

assign add_ln59_5_fu_505_p2 = (add_ln59_17_reg_718 + add_ln59_16_fu_501_p2);

assign add_ln59_6_fu_465_p2 = (c_0_1_read_reg_673 + mul_ln43_3_reg_623);

assign add_ln59_7_fu_408_p2 = (mul_ln43_5_fu_270_p2 + mul_ln43_4_fu_264_p2);

assign add_ln59_9_fu_474_p2 = (c_0_2_read_reg_683 + mul_ln43_6_reg_628);

assign add_ln59_fu_456_p2 = (c_0_0_read_reg_663 + mul_ln43_reg_618);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = $signed(sum_fu_609_p2);

assign product1_2_fu_469_p2 = (add_ln59_7_reg_678 + add_ln59_6_fu_465_p2);

assign product1_4_fu_478_p2 = (add_ln59_10_reg_688 + add_ln59_9_fu_474_p2);

assign product1_8_fu_561_p0 = (add_ln59_13_reg_698 + add_ln59_12_fu_483_p2);

assign product1_fu_460_p2 = (add_ln59_1_reg_668 + add_ln59_fu_456_p2);

assign product2_2_fu_523_p2 = (add_ln59_22_reg_738 + add_ln59_21_fu_519_p2);

assign product2_4_fu_532_p2 = (add_ln59_25_reg_748 + add_ln59_24_fu_528_p2);

assign product2_6_fu_543_p0 = (add_ln59_15_reg_708 + add_ln59_14_fu_492_p2);

assign product2_fu_514_p2 = (add_ln59_19_reg_728 + add_ln59_18_fu_510_p2);

assign sum_fu_609_p2 = (sumneg_fu_605_p2 - product2_5_reg_803);

assign sumneg_fu_605_p2 = (add_ln24_reg_813 + sumpos_3_reg_808);

assign sumpos_3_fu_594_p0 = (product1_8_reg_793 - product2_7_reg_788);

assign sumpos_fu_585_p0 = (product1_7_reg_783 - product2_6_reg_778);

endmodule //matrixcalc
