// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.792000,HLS_SYN_LAT=312,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=111,HLS_SYN_LUT=689,HLS_VERSION=2023_1}" *)

module matrixcalc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        c_address0,
        c_ce0,
        c_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] a_address0;
output   a_ce0;
input  [3:0] a_q0;
output  [3:0] b_address0;
output   b_ce0;
input  [3:0] b_q0;
output  [3:0] c_address0;
output   c_ce0;
input  [3:0] c_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_ce0;
reg b_ce0;
reg c_ce0;

(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] grp_fu_263_p2;
reg   [3:0] reg_178;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state16;
wire   [3:0] grp_fu_378_p2;
wire    ap_CS_fsm_state8;
reg   [3:0] reg_190;
wire    ap_CS_fsm_state22;
reg   [3:0] reg_202;
wire    ap_CS_fsm_state21;
reg   [3:0] reg_215;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state15;
reg   [1:0] reg_227;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state10;
reg  signed [3:0] reg_239;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg  signed [3:0] reg_251;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
reg   [3:0] col_reg_346;
wire    ap_CS_fsm_state19;
reg   [2:0] add_ln19_reg_351;
wire    ap_CS_fsm_state18;
reg   [0:0] icmp_ln18_reg_852;
wire   [3:0] sub_ln43_fu_464_p2;
reg   [3:0] sub_ln43_reg_732;
wire   [3:0] zext_ln41_fu_481_p1;
reg   [3:0] zext_ln41_reg_747;
reg   [3:0] res_addr_reg_752;
wire   [3:0] zext_ln43_1_fu_502_p1;
reg   [3:0] zext_ln43_1_reg_760;
wire   [3:0] sub_ln59_fu_553_p2;
reg   [3:0] sub_ln59_reg_778;
reg   [3:0] aux2_addr_reg_817;
wire   [2:0] zext_ln11_fu_607_p1;
reg   [2:0] zext_ln11_reg_825;
wire   [3:0] zext_ln15_fu_617_p1;
reg   [3:0] zext_ln15_reg_833;
wire   [0:0] icmp_ln11_fu_611_p2;
wire   [3:0] sub_ln20_fu_643_p2;
reg   [3:0] sub_ln20_reg_838;
wire    ap_CS_fsm_state17;
wire   [2:0] zext_ln15_1_fu_649_p1;
reg   [2:0] zext_ln15_1_reg_843;
wire   [0:0] icmp_ln18_fu_660_p2;
wire   [0:0] icmp_ln15_fu_654_p2;
wire    ap_CS_fsm_state20;
wire   [1:0] sub_ln21_fu_692_p2;
reg   [1:0] sub_ln21_reg_862;
reg   [3:0] aux_address0;
reg    aux_ce0;
reg    aux_we0;
wire   [3:0] aux_q0;
reg   [3:0] aux2_address0;
reg    aux2_ce0;
reg    aux2_we0;
wire   [3:0] aux2_q0;
wire   [0:0] icmp_ln42_fu_531_p2;
wire   [0:0] icmp_ln37_fu_470_p2;
wire   [0:0] icmp_ln39_fu_491_p2;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln56_fu_559_p2;
wire   [63:0] zext_ln41_1_fu_486_p1;
wire   [63:0] zext_ln43_2_fu_521_p1;
wire   [63:0] zext_ln43_3_fu_526_p1;
wire   [63:0] zext_ln59_2_fu_585_p1;
wire   [63:0] zext_ln20_1_fu_687_p1;
wire   [63:0] zext_ln21_1_fu_715_p1;
reg   [1:0] i_fu_68;
reg   [1:0] i_1_fu_80;
wire   [0:0] icmp_ln58_fu_592_p2;
reg   [3:0] sumpos_fu_84;
reg   [3:0] sumneg_fu_88;
wire    ap_CS_fsm_state23;
reg   [1:0] i_2_fu_92;
reg   [3:0] grp_fu_263_p0;
wire   [3:0] sub_ln43_1_fu_515_p2;
wire  signed [3:0] sext_ln18_fu_682_p1;
wire   [3:0] sub_ln21_1_fu_708_p2;
reg   [3:0] grp_fu_263_p1;
wire   [3:0] zext_ln59_1_fu_580_p1;
reg  signed [3:0] grp_fu_378_p0;
reg  signed [3:0] grp_fu_378_p1;
wire   [3:0] tmp_fu_456_p3;
wire   [3:0] zext_ln43_fu_452_p1;
wire   [1:0] zext_ln41_fu_481_p0;
wire   [3:0] zext_ln41_1_fu_486_p0;
wire   [1:0] icmp_ln39_fu_491_p0;
wire   [1:0] zext_ln43_1_fu_502_p0;
wire   [1:0] tmp_2_fu_507_p1;
wire   [3:0] tmp_2_fu_507_p3;
wire   [3:0] zext_ln43_2_fu_521_p0;
wire   [1:0] icmp_ln42_fu_531_p0;
wire   [3:0] tmp_1_fu_545_p3;
wire   [3:0] zext_ln59_fu_541_p1;
wire   [1:0] zext_ln59_1_fu_580_p0;
wire   [3:0] zext_ln59_2_fu_585_p0;
wire   [1:0] icmp_ln58_fu_592_p0;
wire   [3:0] sum_fu_621_p2;
wire   [3:0] tmp_3_fu_635_p3;
wire   [3:0] zext_ln20_fu_631_p1;
wire   [2:0] icmp_ln18_fu_660_p0;
wire   [2:0] select_ln18_fu_676_p3;
wire   [3:0] tmp_4_fu_701_p3;
wire   [3:0] zext_ln21_fu_698_p1;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
end

matrixcalc_aux_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
aux_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(aux_address0),
    .ce0(aux_ce0),
    .we0(aux_we0),
    .d0(reg_202),
    .q0(aux_q0)
);

matrixcalc_aux_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
aux2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(aux2_address0),
    .ce0(aux2_ce0),
    .we0(aux2_we0),
    .d0(reg_215),
    .q0(aux2_q0)
);

matrixcalc_mul_4s_4s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 4 ))
mul_4s_4s_4_1_1_U1(
    .din0(grp_fu_378_p0),
    .din1(grp_fu_378_p1),
    .dout(grp_fu_378_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_470_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_fu_80 <= 2'd0;
    end else if (((icmp_ln58_fu_592_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        i_1_fu_80 <= reg_227;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_559_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_2_fu_92 <= 2'd0;
    end else if (((icmp_ln15_fu_654_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        i_2_fu_92 <= reg_215;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_68 <= 2'd0;
    end else if (((icmp_ln39_fu_491_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_fu_68 <= reg_227;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_470_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        reg_178 <= 2'd0;
    end else if (((icmp_ln42_fu_531_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        reg_178 <= reg_239;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_178 <= grp_fu_378_p2;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_178 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_491_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        reg_190 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reg_190 <= reg_251;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        reg_190 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_491_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        reg_202 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        reg_202 <= grp_fu_263_p2;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        reg_202 <= grp_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_559_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        reg_215 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_215 <= reg_239;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_215 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd0))) begin
        reg_227 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        reg_227 <= reg_178;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_227 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd0))) begin
        reg_239 <= 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        reg_239 <= grp_fu_378_p2;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_239 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd0))) begin
        reg_251 <= 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        reg_251 <= reg_202;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_251 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_559_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        sumneg_fu_88 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        sumneg_fu_88 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_559_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        sumpos_fu_84 <= 4'd0;
    end else if (((icmp_ln15_fu_654_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        sumpos_fu_84 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln18_reg_852 == 1'd1))) begin
        add_ln19_reg_351 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        aux2_addr_reg_817 <= zext_ln59_2_fu_585_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        col_reg_346 <= grp_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln15_fu_654_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        icmp_ln18_reg_852 <= icmp_ln18_fu_660_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        res_addr_reg_752 <= zext_ln41_1_fu_486_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        sub_ln20_reg_838 <= sub_ln20_fu_643_p2;
        zext_ln15_1_reg_843[1 : 0] <= zext_ln15_1_fu_649_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sub_ln21_reg_862 <= sub_ln21_fu_692_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sub_ln43_reg_732 <= sub_ln43_fu_464_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sub_ln59_reg_778 <= sub_ln59_fu_553_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        zext_ln11_reg_825[1 : 0] <= zext_ln11_fu_607_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd0))) begin
        zext_ln15_reg_833[1 : 0] <= zext_ln15_fu_617_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln41_reg_747[1 : 0] <= zext_ln41_fu_481_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        zext_ln43_1_reg_760[1 : 0] <= zext_ln43_1_fu_502_p1[1 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        aux2_address0 = zext_ln21_1_fu_715_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        aux2_address0 = zext_ln20_1_fu_687_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        aux2_address0 = aux2_addr_reg_817;
    end else begin
        aux2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state20))) begin
        aux2_ce0 = 1'b1;
    end else begin
        aux2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        aux2_we0 = 1'b1;
    end else begin
        aux2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        aux_address0 = zext_ln59_2_fu_585_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        aux_address0 = res_addr_reg_752;
    end else begin
        aux_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state12))) begin
        aux_ce0 = 1'b1;
    end else begin
        aux_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln42_fu_531_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        aux_we0 = 1'b1;
    end else begin
        aux_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_263_p0 = reg_239;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_263_p0 = sub_ln21_1_fu_708_p2;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_263_p0 = sub_ln20_reg_838;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_263_p0 = sext_ln18_fu_682_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_263_p0 = zext_ln15_1_reg_843;
    end else if (((icmp_ln15_fu_654_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_263_p0 = reg_251;
    end else if (((icmp_ln15_fu_654_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_263_p0 = zext_ln15_1_fu_649_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_263_p0 = reg_227;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_263_p0 = i_2_fu_92;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_263_p0 = c_q0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_263_p0 = reg_215;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_263_p0 = sub_ln59_reg_778;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_263_p0 = i_1_fu_80;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_263_p0 = reg_190;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_263_p0 = sub_ln43_1_fu_515_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_263_p0 = reg_178;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_263_p0 = sub_ln43_reg_732;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_263_p0 = i_fu_68;
    end else begin
        grp_fu_263_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_263_p1 = sumneg_fu_88;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_263_p1 = col_reg_346;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_263_p1 = zext_ln15_reg_833;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_263_p1 = 3'd5;
    end else if (((icmp_ln15_fu_654_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_263_p1 = sumpos_fu_84;
    end else if (((icmp_ln15_fu_654_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_263_p1 = zext_ln11_reg_825;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_263_p1 = aux_q0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_263_p1 = zext_ln59_1_fu_580_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_263_p1 = reg_202;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_263_p1 = zext_ln41_reg_747;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_263_p1 = zext_ln43_1_fu_502_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_263_p1 = zext_ln41_fu_481_p1;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state15))) begin
        grp_fu_263_p1 = 2'd1;
    end else begin
        grp_fu_263_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        grp_fu_378_p0 = aux2_q0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_378_p0 = b_q0;
    end else begin
        grp_fu_378_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_378_p1 = reg_239;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_378_p1 = reg_251;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_378_p1 = a_q0;
    end else begin
        grp_fu_378_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln37_fu_470_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln39_fu_491_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln42_fu_531_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln56_fu_559_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln58_fu_592_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln11_fu_611_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln15_fu_654_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = zext_ln43_2_fu_521_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = $signed(sum_fu_621_p2);

assign b_address0 = zext_ln43_3_fu_526_p1;

assign c_address0 = zext_ln59_2_fu_585_p1;

assign grp_fu_263_p2 = (grp_fu_263_p0 + grp_fu_263_p1);

assign icmp_ln11_fu_611_p2 = ((i_2_fu_92 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_654_p2 = ((reg_227 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_660_p0 = grp_fu_263_p2;

assign icmp_ln18_fu_660_p2 = ((icmp_ln18_fu_660_p0 > 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_470_p2 = ((i_fu_68 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_491_p0 = reg_178;

assign icmp_ln39_fu_491_p2 = ((icmp_ln39_fu_491_p0 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_531_p0 = reg_190;

assign icmp_ln42_fu_531_p2 = ((icmp_ln42_fu_531_p0 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_559_p2 = ((i_1_fu_80 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_592_p0 = reg_215;

assign icmp_ln58_fu_592_p2 = ((icmp_ln58_fu_592_p0 == 2'd3) ? 1'b1 : 1'b0);

assign select_ln18_fu_676_p3 = ((icmp_ln18_reg_852[0:0] == 1'b1) ? add_ln19_reg_351 : zext_ln15_1_reg_843);

assign sext_ln18_fu_682_p1 = $signed(select_ln18_fu_676_p3);

assign sub_ln20_fu_643_p2 = (tmp_3_fu_635_p3 - zext_ln20_fu_631_p1);

assign sub_ln21_1_fu_708_p2 = (tmp_4_fu_701_p3 - zext_ln21_fu_698_p1);

assign sub_ln21_fu_692_p2 = ($signed(2'd2) - $signed(reg_227));

assign sub_ln43_1_fu_515_p2 = (tmp_2_fu_507_p3 - zext_ln43_1_reg_760);

assign sub_ln43_fu_464_p2 = (tmp_fu_456_p3 - zext_ln43_fu_452_p1);

assign sub_ln59_fu_553_p2 = (tmp_1_fu_545_p3 - zext_ln59_fu_541_p1);

assign sum_fu_621_p2 = (sumpos_fu_84 - sumneg_fu_88);

assign tmp_1_fu_545_p3 = {{i_1_fu_80}, {2'd0}};

assign tmp_2_fu_507_p1 = reg_190;

assign tmp_2_fu_507_p3 = {{tmp_2_fu_507_p1}, {2'd0}};

assign tmp_3_fu_635_p3 = {{reg_227}, {2'd0}};

assign tmp_4_fu_701_p3 = {{sub_ln21_reg_862}, {2'd0}};

assign tmp_fu_456_p3 = {{i_fu_68}, {2'd0}};

assign zext_ln11_fu_607_p1 = i_2_fu_92;

assign zext_ln15_1_fu_649_p1 = reg_227;

assign zext_ln15_fu_617_p1 = i_2_fu_92;

assign zext_ln20_1_fu_687_p1 = grp_fu_263_p2;

assign zext_ln20_fu_631_p1 = reg_227;

assign zext_ln21_1_fu_715_p1 = grp_fu_263_p2;

assign zext_ln21_fu_698_p1 = sub_ln21_reg_862;

assign zext_ln41_1_fu_486_p0 = reg_239;

assign zext_ln41_1_fu_486_p1 = zext_ln41_1_fu_486_p0;

assign zext_ln41_fu_481_p0 = reg_178;

assign zext_ln41_fu_481_p1 = zext_ln41_fu_481_p0;

assign zext_ln43_1_fu_502_p0 = reg_190;

assign zext_ln43_1_fu_502_p1 = zext_ln43_1_fu_502_p0;

assign zext_ln43_2_fu_521_p0 = reg_251;

assign zext_ln43_2_fu_521_p1 = zext_ln43_2_fu_521_p0;

assign zext_ln43_3_fu_526_p1 = reg_178;

assign zext_ln43_fu_452_p1 = i_fu_68;

assign zext_ln59_1_fu_580_p0 = reg_215;

assign zext_ln59_1_fu_580_p1 = zext_ln59_1_fu_580_p0;

assign zext_ln59_2_fu_585_p0 = reg_239;

assign zext_ln59_2_fu_585_p1 = zext_ln59_2_fu_585_p0;

assign zext_ln59_fu_541_p1 = i_1_fu_80;

always @ (posedge ap_clk) begin
    zext_ln41_reg_747[3:2] <= 2'b00;
    zext_ln43_1_reg_760[3:2] <= 2'b00;
    zext_ln11_reg_825[2] <= 1'b0;
    zext_ln15_reg_833[3:2] <= 2'b00;
    zext_ln15_1_reg_843[2] <= 1'b0;
end

endmodule //matrixcalc
