#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("a_0_0", 4, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("a_0_1", 4, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("a_0_2", 4, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("a_1_0", 4, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("a_1_1", 4, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("a_1_2", 4, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("a_2_0", 4, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("a_2_1", 4, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("a_2_2", 4, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("b_0_0", 4, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("b_0_1", 4, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("b_0_2", 4, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("b_1_0", 4, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("b_1_1", 4, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("b_1_2", 4, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("b_2_0", 4, hls_in, 15, "ap_none", "in_data", 1),
	Port_Property("b_2_1", 4, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("b_2_2", 4, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("c_0_0", 4, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("c_0_1", 4, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("c_0_2", 4, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("c_1_0", 4, hls_in, 21, "ap_none", "in_data", 1),
	Port_Property("c_1_1", 4, hls_in, 22, "ap_none", "in_data", 1),
	Port_Property("c_1_2", 4, hls_in, 23, "ap_none", "in_data", 1),
	Port_Property("c_2_0", 4, hls_in, 24, "ap_none", "in_data", 1),
	Port_Property("c_2_1", 4, hls_in, 25, "ap_none", "in_data", 1),
	Port_Property("c_2_2", 4, hls_in, 26, "ap_none", "in_data", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "matrixcalc";
