-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrixcalc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    c_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    c_ce0 : OUT STD_LOGIC;
    c_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrixcalc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrixcalc_matrixcalc,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.792000,HLS_SYN_LAT=312,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=111,HLS_SYN_LUT=689,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (22 downto 0) := "00000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (22 downto 0) := "00000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (22 downto 0) := "00000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (22 downto 0) := "00000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (22 downto 0) := "00000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (22 downto 0) := "00000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (22 downto 0) := "00001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (22 downto 0) := "00010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (22 downto 0) := "00100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (22 downto 0) := "01000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (22 downto 0) := "10000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_263_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal reg_178 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_fu_378_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal reg_190 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal reg_202 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal reg_215 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal reg_227 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal reg_239 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal reg_251 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal col_reg_346 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal add_ln19_reg_351 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal icmp_ln18_reg_852 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln43_fu_464_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln43_reg_732 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln41_fu_481_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln41_reg_747 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_addr_reg_752 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln43_1_fu_502_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln43_1_reg_760 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln59_fu_553_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln59_reg_778 : STD_LOGIC_VECTOR (3 downto 0);
    signal aux2_addr_reg_817 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_fu_607_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_reg_825 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln15_fu_617_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln15_reg_833 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln11_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln20_fu_643_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln20_reg_838 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal zext_ln15_1_fu_649_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln15_1_reg_843 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln18_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln15_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal sub_ln21_fu_692_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln21_reg_862 : STD_LOGIC_VECTOR (1 downto 0);
    signal aux_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal aux_ce0 : STD_LOGIC;
    signal aux_we0 : STD_LOGIC;
    signal aux_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal aux2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal aux2_ce0 : STD_LOGIC;
    signal aux2_we0 : STD_LOGIC;
    signal aux2_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln42_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal icmp_ln56_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln41_1_fu_486_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_2_fu_521_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_3_fu_526_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln59_2_fu_585_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_1_fu_687_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_1_fu_715_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_1_fu_80 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln58_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sumpos_fu_84 : STD_LOGIC_VECTOR (3 downto 0);
    signal sumneg_fu_88 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal i_2_fu_92 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_263_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln43_1_fu_515_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln18_fu_682_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln21_1_fu_708_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_263_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln59_1_fu_580_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_378_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_378_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_456_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln43_fu_452_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln41_fu_481_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln41_1_fu_486_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln39_fu_491_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln43_1_fu_502_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_507_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_507_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln43_2_fu_521_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln42_fu_531_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_545_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln59_fu_541_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln59_1_fu_580_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln59_2_fu_585_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln58_fu_592_p0 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_fu_621_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_635_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln20_fu_631_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln18_fu_660_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln18_fu_676_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_4_fu_701_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln21_fu_698_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrixcalc_mul_4s_4s_4_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component matrixcalc_aux_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    aux_U : component matrixcalc_aux_RAM_AUTO_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => aux_address0,
        ce0 => aux_ce0,
        we0 => aux_we0,
        d0 => reg_202,
        q0 => aux_q0);

    aux2_U : component matrixcalc_aux_RAM_AUTO_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => aux2_address0,
        ce0 => aux2_ce0,
        we0 => aux2_we0,
        d0 => reg_215,
        q0 => aux2_q0);

    mul_4s_4s_4_1_1_U1 : component matrixcalc_mul_4s_4s_4_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        din0 => grp_fu_378_p0,
        din1 => grp_fu_378_p1,
        dout => grp_fu_378_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_1_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_1_fu_80 <= ap_const_lv2_0;
            elsif (((icmp_ln58_fu_592_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                i_1_fu_80 <= reg_227;
            end if; 
        end if;
    end process;

    i_2_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln56_fu_559_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                i_2_fu_92 <= ap_const_lv2_0;
            elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                i_2_fu_92 <= reg_215(2 - 1 downto 0);
            end if; 
        end if;
    end process;

    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_68 <= ap_const_lv2_0;
            elsif (((icmp_ln39_fu_491_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_fu_68 <= reg_227;
            end if; 
        end if;
    end process;

    reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_fu_470_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                reg_178 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv2_0),4));
            elsif (((icmp_ln42_fu_531_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                reg_178 <= reg_239;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                reg_178 <= grp_fu_378_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                reg_178 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;

    reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                reg_190 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv2_0),4));
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                reg_190 <= reg_251;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                reg_190 <= grp_fu_378_p2;
            end if; 
        end if;
    end process;

    reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                reg_202 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                reg_202 <= grp_fu_263_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                reg_202 <= grp_fu_378_p2;
            end if; 
        end if;
    end process;

    reg_215_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln56_fu_559_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                reg_215 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv2_0),4));
            elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                reg_215 <= reg_239;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                reg_215 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;

    reg_227_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_0))) then 
                reg_227 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                reg_227 <= reg_178(2 - 1 downto 0);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                reg_227 <= grp_fu_263_p2(2 - 1 downto 0);
            end if; 
        end if;
    end process;

    reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_0))) then 
                reg_239 <= ap_const_lv4_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                reg_239 <= grp_fu_378_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                reg_239 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;

    reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_0))) then 
                reg_251 <= ap_const_lv4_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
                reg_251 <= reg_202;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                reg_251 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;

    sumneg_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln56_fu_559_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                sumneg_fu_88 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
                sumneg_fu_88 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;

    sumpos_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln56_fu_559_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                sumpos_fu_84 <= ap_const_lv4_0;
            elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                sumpos_fu_84 <= grp_fu_263_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state18) and (icmp_ln18_reg_852 = ap_const_lv1_1))) then
                add_ln19_reg_351 <= grp_fu_263_p2(3 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                aux2_addr_reg_817 <= zext_ln59_2_fu_585_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                col_reg_346 <= grp_fu_263_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln15_fu_654_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                icmp_ln18_reg_852 <= icmp_ln18_fu_660_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                res_addr_reg_752 <= zext_ln41_1_fu_486_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                sub_ln20_reg_838 <= sub_ln20_fu_643_p2;
                    zext_ln15_1_reg_843(1 downto 0) <= zext_ln15_1_fu_649_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                sub_ln21_reg_862 <= sub_ln21_fu_692_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                sub_ln43_reg_732 <= sub_ln43_fu_464_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                sub_ln59_reg_778 <= sub_ln59_fu_553_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                    zext_ln11_reg_825(1 downto 0) <= zext_ln11_fu_607_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_0))) then
                    zext_ln15_reg_833(1 downto 0) <= zext_ln15_fu_617_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    zext_ln41_reg_747(1 downto 0) <= zext_ln41_fu_481_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    zext_ln43_1_reg_760(1 downto 0) <= zext_ln43_1_fu_502_p1(1 downto 0);
            end if;
        end if;
    end process;
    zext_ln41_reg_747(3 downto 2) <= "00";
    zext_ln43_1_reg_760(3 downto 2) <= "00";
    zext_ln11_reg_825(2) <= '0';
    zext_ln15_reg_833(3 downto 2) <= "00";
    zext_ln15_1_reg_843(2) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state15, ap_CS_fsm_state2, ap_CS_fsm_state10, ap_CS_fsm_state4, ap_CS_fsm_state12, ap_CS_fsm_state7, icmp_ln11_fu_611_p2, ap_CS_fsm_state17, icmp_ln15_fu_654_p2, icmp_ln42_fu_531_p2, icmp_ln37_fu_470_p2, icmp_ln39_fu_491_p2, icmp_ln56_fu_559_p2, icmp_ln58_fu_592_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln37_fu_470_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln39_fu_491_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln42_fu_531_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state10 => 
                if (((icmp_ln56_fu_559_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((icmp_ln58_fu_592_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln15_fu_654_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state23;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    a_address0 <= zext_ln43_2_fu_521_p1(4 - 1 downto 0);

    a_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            a_ce0 <= ap_const_logic_1;
        else 
            a_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state15, icmp_ln11_fu_611_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state15, icmp_ln11_fu_611_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) and (icmp_ln11_fu_611_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        ap_return <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_fu_621_p2),32));


    aux2_address0_assign_proc : process(ap_CS_fsm_state21, aux2_addr_reg_817, ap_CS_fsm_state20, ap_CS_fsm_state14, zext_ln20_1_fu_687_p1, zext_ln21_1_fu_715_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            aux2_address0 <= zext_ln21_1_fu_715_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            aux2_address0 <= zext_ln20_1_fu_687_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            aux2_address0 <= aux2_addr_reg_817;
        else 
            aux2_address0 <= "XXXX";
        end if; 
    end process;


    aux2_ce0_assign_proc : process(ap_CS_fsm_state21, ap_CS_fsm_state20, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            aux2_ce0 <= ap_const_logic_1;
        else 
            aux2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    aux2_we0_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            aux2_we0 <= ap_const_logic_1;
        else 
            aux2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    aux_address0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state7, res_addr_reg_752, zext_ln59_2_fu_585_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            aux_address0 <= zext_ln59_2_fu_585_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            aux_address0 <= res_addr_reg_752;
        else 
            aux_address0 <= "XXXX";
        end if; 
    end process;


    aux_ce0_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            aux_ce0 <= ap_const_logic_1;
        else 
            aux_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    aux_we0_assign_proc : process(ap_CS_fsm_state7, icmp_ln42_fu_531_p2)
    begin
        if (((icmp_ln42_fu_531_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            aux_we0 <= ap_const_logic_1;
        else 
            aux_we0 <= ap_const_logic_0;
        end if; 
    end process;

    b_address0 <= zext_ln43_3_fu_526_p1(4 - 1 downto 0);

    b_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            b_ce0 <= ap_const_logic_1;
        else 
            b_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    c_address0 <= zext_ln59_2_fu_585_p1(4 - 1 downto 0);

    c_ce0_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            c_ce0 <= ap_const_logic_1;
        else 
            c_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_263_p0_assign_proc : process(c_q0, reg_178, ap_CS_fsm_state6, ap_CS_fsm_state16, reg_190, ap_CS_fsm_state21, reg_215, ap_CS_fsm_state9, ap_CS_fsm_state13, ap_CS_fsm_state15, reg_227, ap_CS_fsm_state2, ap_CS_fsm_state10, reg_239, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state11, ap_CS_fsm_state12, reg_251, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state19, ap_CS_fsm_state18, sub_ln43_reg_732, sub_ln59_reg_778, sub_ln20_reg_838, ap_CS_fsm_state17, zext_ln15_1_fu_649_p1, zext_ln15_1_reg_843, icmp_ln15_fu_654_p2, ap_CS_fsm_state20, i_fu_68, i_1_fu_80, ap_CS_fsm_state23, i_2_fu_92, sub_ln43_1_fu_515_p2, sext_ln18_fu_682_p1, sub_ln21_1_fu_708_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            grp_fu_263_p0 <= reg_239;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_263_p0 <= sub_ln21_1_fu_708_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            grp_fu_263_p0 <= sub_ln20_reg_838;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_263_p0 <= sext_ln18_fu_682_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln15_1_reg_843),4));
        elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_263_p0 <= reg_251;
        elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln15_1_fu_649_p1),4));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_227),4));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_92),4));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_263_p0 <= c_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_263_p0 <= reg_215;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_263_p0 <= sub_ln59_reg_778;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_80),4));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_263_p0 <= reg_190;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_263_p0 <= sub_ln43_1_fu_515_p2;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_263_p0 <= reg_178;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_fu_263_p0 <= sub_ln43_reg_732;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_263_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_68),4));
        else 
            grp_fu_263_p0 <= "XXXX";
        end if; 
    end process;


    grp_fu_263_p1_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state16, reg_202, ap_CS_fsm_state21, ap_CS_fsm_state9, ap_CS_fsm_state13, ap_CS_fsm_state15, ap_CS_fsm_state2, ap_CS_fsm_state10, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state5, ap_CS_fsm_state7, col_reg_346, ap_CS_fsm_state19, ap_CS_fsm_state18, zext_ln41_fu_481_p1, zext_ln41_reg_747, zext_ln43_1_fu_502_p1, zext_ln11_reg_825, zext_ln15_reg_833, ap_CS_fsm_state17, icmp_ln15_fu_654_p2, ap_CS_fsm_state20, aux_q0, sumpos_fu_84, sumneg_fu_88, ap_CS_fsm_state23, zext_ln59_1_fu_580_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            grp_fu_263_p1 <= sumneg_fu_88;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            grp_fu_263_p1 <= col_reg_346;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_263_p1 <= zext_ln15_reg_833;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            grp_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv3_5),4));
        elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_263_p1 <= sumpos_fu_84;
        elsif (((icmp_ln15_fu_654_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            grp_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln11_reg_825),4));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_263_p1 <= aux_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_263_p1 <= zext_ln59_1_fu_580_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_263_p1 <= reg_202;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_263_p1 <= zext_ln41_reg_747;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_263_p1 <= zext_ln43_1_fu_502_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_263_p1 <= zext_ln41_fu_481_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state15))) then 
            grp_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_const_lv2_1),4));
        else 
            grp_fu_263_p1 <= "XXXX";
        end if; 
    end process;

    grp_fu_263_p2 <= std_logic_vector(unsigned(grp_fu_263_p0) + unsigned(grp_fu_263_p1));

    grp_fu_378_p0_assign_proc : process(b_q0, ap_CS_fsm_state8, ap_CS_fsm_state22, ap_CS_fsm_state21, aux2_q0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state22))) then 
            grp_fu_378_p0 <= aux2_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_378_p0 <= b_q0;
        else 
            grp_fu_378_p0 <= "XXXX";
        end if; 
    end process;


    grp_fu_378_p1_assign_proc : process(a_q0, ap_CS_fsm_state8, ap_CS_fsm_state22, ap_CS_fsm_state21, reg_239, reg_251)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            grp_fu_378_p1 <= reg_239;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_378_p1 <= reg_251;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_378_p1 <= a_q0;
        else 
            grp_fu_378_p1 <= "XXXX";
        end if; 
    end process;

    icmp_ln11_fu_611_p2 <= "1" when (i_2_fu_92 = ap_const_lv2_3) else "0";
    icmp_ln15_fu_654_p2 <= "1" when (reg_227 = ap_const_lv2_3) else "0";
    icmp_ln18_fu_660_p0 <= grp_fu_263_p2(3 - 1 downto 0);
    icmp_ln18_fu_660_p2 <= "1" when (unsigned(icmp_ln18_fu_660_p0) > unsigned(ap_const_lv3_2)) else "0";
    icmp_ln37_fu_470_p2 <= "1" when (i_fu_68 = ap_const_lv2_3) else "0";
    icmp_ln39_fu_491_p0 <= reg_178(2 - 1 downto 0);
    icmp_ln39_fu_491_p2 <= "1" when (icmp_ln39_fu_491_p0 = ap_const_lv2_3) else "0";
    icmp_ln42_fu_531_p0 <= reg_190(2 - 1 downto 0);
    icmp_ln42_fu_531_p2 <= "1" when (icmp_ln42_fu_531_p0 = ap_const_lv2_3) else "0";
    icmp_ln56_fu_559_p2 <= "1" when (i_1_fu_80 = ap_const_lv2_3) else "0";
    icmp_ln58_fu_592_p0 <= reg_215(2 - 1 downto 0);
    icmp_ln58_fu_592_p2 <= "1" when (icmp_ln58_fu_592_p0 = ap_const_lv2_3) else "0";
    select_ln18_fu_676_p3 <= 
        add_ln19_reg_351 when (icmp_ln18_reg_852(0) = '1') else 
        zext_ln15_1_reg_843;
        sext_ln18_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_676_p3),4));

    sub_ln20_fu_643_p2 <= std_logic_vector(unsigned(tmp_3_fu_635_p3) - unsigned(zext_ln20_fu_631_p1));
    sub_ln21_1_fu_708_p2 <= std_logic_vector(unsigned(tmp_4_fu_701_p3) - unsigned(zext_ln21_fu_698_p1));
    sub_ln21_fu_692_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(reg_227));
    sub_ln43_1_fu_515_p2 <= std_logic_vector(unsigned(tmp_2_fu_507_p3) - unsigned(zext_ln43_1_reg_760));
    sub_ln43_fu_464_p2 <= std_logic_vector(unsigned(tmp_fu_456_p3) - unsigned(zext_ln43_fu_452_p1));
    sub_ln59_fu_553_p2 <= std_logic_vector(unsigned(tmp_1_fu_545_p3) - unsigned(zext_ln59_fu_541_p1));
    sum_fu_621_p2 <= std_logic_vector(unsigned(sumpos_fu_84) - unsigned(sumneg_fu_88));
    tmp_1_fu_545_p3 <= (i_1_fu_80 & ap_const_lv2_0);
    tmp_2_fu_507_p1 <= reg_190(2 - 1 downto 0);
    tmp_2_fu_507_p3 <= (tmp_2_fu_507_p1 & ap_const_lv2_0);
    tmp_3_fu_635_p3 <= (reg_227 & ap_const_lv2_0);
    tmp_4_fu_701_p3 <= (sub_ln21_reg_862 & ap_const_lv2_0);
    tmp_fu_456_p3 <= (i_fu_68 & ap_const_lv2_0);
    zext_ln11_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_92),3));
    zext_ln15_1_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_227),3));
    zext_ln15_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_fu_92),4));
    zext_ln20_1_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_263_p2),64));
    zext_ln20_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_227),4));
    zext_ln21_1_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_263_p2),64));
    zext_ln21_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln21_reg_862),4));
    zext_ln41_1_fu_486_p0 <= reg_239;
    zext_ln41_1_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln41_1_fu_486_p0),64));
    zext_ln41_fu_481_p0 <= reg_178(2 - 1 downto 0);
    zext_ln41_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln41_fu_481_p0),4));
    zext_ln43_1_fu_502_p0 <= reg_190(2 - 1 downto 0);
    zext_ln43_1_fu_502_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln43_1_fu_502_p0),4));
    zext_ln43_2_fu_521_p0 <= reg_251;
    zext_ln43_2_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln43_2_fu_521_p0),64));
    zext_ln43_3_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_178),64));
    zext_ln43_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_68),4));
    zext_ln59_1_fu_580_p0 <= reg_215(2 - 1 downto 0);
    zext_ln59_1_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln59_1_fu_580_p0),4));
    zext_ln59_2_fu_585_p0 <= reg_239;
    zext_ln59_2_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln59_2_fu_585_p0),64));
    zext_ln59_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_80),4));
end behav;
